#region Certificate Services Extended Audits (ESC4, ESC8, ROCA, weak PKI crypto)
#
# Extends src/CertificateServicesAudits.ps1 (ESC1/ESC2/ESC3/ESC7) with the
# remaining PingCastle-comparable AD CS checks:
#
#   - ESC4  : dangerous ACLs on certificate templates (Write/WriteDacl/
#             WriteOwner/GenericAll/GenericWrite granted to low-privileged
#             principals), which let an attacker rewrite a template into an
#             ESC1-style template.
#   - ESC8  : CA web enrollment reachable over HTTP without Extended
#             Protection for Authentication (EPA), enabling NTLM relay to
#             the enrollment endpoint.
#   - A high-risk-without-approval check that flags templates combining
#     enrollee-supplied subject/SAN or an Any-Purpose EKU with no manager
#     approval gate (CT_FLAG_PEND_ALL_REQUESTS unset). This is deliberately
#     scoped differently from the existing ESC1 (SAN + low-priv enrollment)
#     and ESC2 (no EKU / Any-Purpose) checks so it does not duplicate them.
#   - ROCA-vulnerable keys (CVE-2017-15361) and weak signature algorithms /
#     RSA moduli across the CA certificates, NTAuth store, and AIA/Root
#     store published in the Configuration partition.
#
# PingCastle-comparable check(s): A-CertEnrollHttp, A-CertTempNoSecurity,
# A-CertTempAnyPurpose, A-CertTempAnyone, A-CertTempCustomSubject,
# A-CertROCA, A-CertWeakRsaComponent, A-MD5RootCert, A-SHA1RootCert.
#
# DETECTION ONLY: every check here reads AD attributes/ACLs, certificate
# bytes already published in AD, or (for ESC8 only) remote service/registry
# state on the CA host itself. Nothing here requests, forges, or relays a
# certificate, and no coercion/PoC traffic is sent to any host.
#
# Snapshot contract: certificate template/CA enumeration and the
# attribute-only checks (approval-gate check, and weak-signature/ROCA
# evaluation of the CA's own published certificate) are snapshot-aware via
# Snapshot.ADCS (from Get-ADSnapshot, unchanged schema). ESC4 (per-template
# ACL), ESC8 (live network probe of the CA host), and the NTAuth/AIA/Root
# store sweep are live AD/network reads with no snapshot representation, so
# - consistent with the anonymous-bind probe in Test-ADDomainHardeningFlags
# and the per-DC probes in Test-ADCoercionAndRelayExposure - they are
# skipped entirely when this function is invoked with -Snapshot.

# Small set of primes (with a fast brute-force order computation, valid
# since each prime here is tiny) used for a probabilistic ROCA fingerprint
# test. A modulus is treated as a ROCA candidate only when the discrete-log
# style test below holds for every one of these primes; this mirrors the
# public description of the ROCA (CVE-2017-15361) fingerprinting technique
# but is a heuristic re-implementation, not a copy of any vendor/tool code.
$Script:ADCSRocaTestPrimes = @(3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,101,103,107,109,113)

function ConvertTo-ADCSBigInteger {
    <#
    .SYNOPSIS
        Converts a big-endian unsigned byte array (as returned by
        RSAParameters.Modulus) into a positive [System.Numerics.BigInteger].
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [byte[]]$BigEndianBytes
    )

    $little = [byte[]]$BigEndianBytes.Clone()
    [Array]::Reverse($little)
    # Append a trailing zero byte so BigInteger (which is little-endian,
    # two's-complement) never interprets the value as negative.
    $withSign = New-Object byte[] ($little.Length + 1)
    [Array]::Copy($little, $withSign, $little.Length)
    return [System.Numerics.BigInteger]::new($withSign)
}

function Test-ADCSRocaFingerprint {
    <#
    .SYNOPSIS
        Heuristic ROCA (CVE-2017-15361) fingerprint test for an RSA modulus.
    .DESCRIPTION
        For each small prime p in $Script:ADCSRocaTestPrimes, computes the
        multiplicative order of 65537 mod p, then checks whether
        (N mod p) raised to that order is congruent to 1 mod p - the
        signature of a modulus generated by the affected Infineon RSALib
        key-generation routine. Flags the modulus only when the test holds
        for every prime evaluated. This is a probabilistic filter (as the
        public description of ROCA detection is), not a certainty; genuine
        candidates should be confirmed with a dedicated ROCA-detection tool
        before remediation is prioritised.
    .OUTPUTS
        [bool]
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [System.Numerics.BigInteger]$Modulus
    )

    $tested = 0
    $matched = 0

    foreach ($p in $Script:ADCSRocaTestPrimes) {
        $pBig = [System.Numerics.BigInteger]$p
        $g = [System.Numerics.BigInteger]65537 % $pBig
        if ($g -eq [System.Numerics.BigInteger]0) { continue }

        # Brute-force multiplicative order of g mod p (p is tiny, so this
        # is at most p-1 iterations).
        $order = 1
        $val = $g
        while ($val -ne [System.Numerics.BigInteger]1 -and $order -le $p) {
            $val = ($val * $g) % $pBig
            $order++
        }

        $nModP = $Modulus % $pBig
        if ($nModP -eq [System.Numerics.BigInteger]0) { continue }

        $tested++
        $result = [System.Numerics.BigInteger]::ModPow($nModP, $order, $pBig)
        if ($result -eq [System.Numerics.BigInteger]1) {
            $matched++
        }
    }

    if ($tested -eq 0) { return $false }
    return ($matched -eq $tested)
}

function Get-ADCSCertificateBlob {
    <#
    .SYNOPSIS
        Reads raw certificate bytes (cACertificate) from a PKI container
        object and, where present, its immediate child objects.
    .DESCRIPTION
        Used for the NTAuthCertificates object (a single object holding a
        multivalued cACertificate attribute) as well as the AIA and Root
        Certification Authorities containers (whose children each carry
        their own cACertificate). Failures are non-terminating and reported
        via Write-Verbose; a missing/inaccessible container simply yields
        no blobs.
    .OUTPUTS
        [PSCustomObject[]] with Source and Bytes properties.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$ContainerDN,

        [Parameter()]
        [string]$Server
    )

    $blobs = [System.Collections.ArrayList]::new()

    try {
        $obj = Get-ADObject -Identity $ContainerDN -Properties cACertificate, cn -Server $Server -ErrorAction Stop
        foreach ($b in @($obj.cACertificate)) {
            if ($b) { [void]$blobs.Add([PSCustomObject]@{ Source = $obj.Name; Bytes = $b }) }
        }
    }
    catch {
        Write-Verbose "Get-ADCSCertificateBlob: could not read '$ContainerDN' directly: $_"
    }

    try {
        $children = Get-ADObject -SearchBase $ContainerDN -SearchScope OneLevel -Filter * -Properties cACertificate, cn -Server $Server -ErrorAction Stop
        foreach ($child in $children) {
            foreach ($b in @($child.cACertificate)) {
                if ($b) { [void]$blobs.Add([PSCustomObject]@{ Source = $child.Name; Bytes = $b }) }
            }
        }
    }
    catch {
        Write-Verbose "Get-ADCSCertificateBlob: could not enumerate children of '$ContainerDN': $_"
    }

    return @($blobs)
}

function Test-ADCSWeakCertificate {
    <#
    .SYNOPSIS
        Evaluates one certificate blob for weak signature algorithm, weak
        RSA modulus size, and the ROCA fingerprint.
    .OUTPUTS
        [PSCustomObject] describing what (if anything) is weak, or $null if
        the blob could not be parsed as a certificate.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [byte[]]$Bytes,

        [Parameter(Mandatory)]
        [string]$Source
    )

    try {
        $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2(,$Bytes)
    }
    catch {
        Write-Verbose "Test-ADCSWeakCertificate: could not parse certificate from '$Source': $_"
        return $null
    }

    $sigAlgo = $cert.SignatureAlgorithm.FriendlyName
    $weakSig = $sigAlgo -match '(?i)md2|md4|md5|sha0|sha1\b'

    $isRoca = $false
    $keySize = $null
    $weakModulus = $false

    try {
        $rsa = $null
        try {
            # .NET 4.6+ extension method; not resolvable on hosts with an
            # older .NET Framework, where PowerShell reports "does not
            # contain a method named 'GetRSAPublicKey'" even though the
            # certificate itself is fine.
            $rsa = $cert.GetRSAPublicKey()
        }
        catch {
            $rsa = $null
        }
        if (-not $rsa) {
            # Fallback for older .NET Framework: the legacy (deprecated but
            # universally available since .NET 2.0) PublicKey.Key API still
            # returns an RSACryptoServiceProvider for RSA certificates.
            try {
                $legacyKey = $cert.PublicKey.Key
                if ($legacyKey -is [System.Security.Cryptography.RSACryptoServiceProvider]) {
                    $rsa = $legacyKey
                }
            }
            catch {
                Write-Verbose "Test-ADCSWeakCertificate: legacy PublicKey.Key fallback also failed for '$Source': $_"
            }
        }
        if ($rsa) {
            $keySize = $rsa.KeySize
            $weakModulus = $keySize -lt 2048
            $rsaParams = $rsa.ExportParameters($false)
            $modulusBig = ConvertTo-ADCSBigInteger -BigEndianBytes $rsaParams.Modulus
            $isRoca = Test-ADCSRocaFingerprint -Modulus $modulusBig
        }
    }
    catch {
        Write-Verbose "Test-ADCSWeakCertificate: could not evaluate RSA public key for '$Source': $_"
    }

    if (-not ($weakSig -or $weakModulus -or $isRoca)) {
        return $null
    }

    return [PSCustomObject]@{
        Source           = $Source
        Subject          = $cert.Subject
        Thumbprint       = $cert.Thumbprint
        NotAfter         = $cert.NotAfter
        SignatureAlgorithm = $sigAlgo
        KeySize          = $keySize
        WeakSignature    = $weakSig
        WeakModulus      = $weakModulus
        RocaCandidate    = $isRoca
    }
}

function Test-ADCSExtended {
    <#
    .SYNOPSIS
        Audits AD CS for ESC4, ESC8, ROCA-vulnerable keys, and weak
        signature algorithms / RSA moduli across the CA and trust store.
    .DESCRIPTION
        Extends the existing ESC1/ESC2/ESC3/ESC7 coverage in
        Test-ADCertificateServices with:
          - ESC4: certificate templates whose ACL grants Write/WriteDacl/
            WriteOwner/GenericAll/GenericWrite to a low-privileged
            principal.
          - A high-risk-without-approval check: templates that allow an
            enrollee-supplied subject/SAN or carry an Any-Purpose EKU
            without requiring manager approval (CT_FLAG_PEND_ALL_REQUESTS).
          - ESC8: CA web enrollment reachable over HTTP without Extended
            Protection for Authentication.
          - ROCA-vulnerable keys (CVE-2017-15361) and weak signature
            algorithms / RSA key sizes across the CA certificates, the
            NTAuthCertificates object, and the AIA/Root store.

        Detection only - reads template/CA attributes, ACLs, and published
        certificate bytes, plus (ESC8 only) remote service/web-configuration
        state on the CA host. Never requests, forges, or relays a
        certificate, and sends no coercion/PoC traffic.
    .PARAMETER Snapshot
        Optional snapshot hashtable (from Get-ADSnapshot). When supplied,
        certificate template/CA enumeration, ESC4 (per-template ACL), the
        approval-gate/CA-certificate weak-crypto checks, and the NTAuth/AIA/
        Root store sweep are all read from Snapshot.ADCS - no live AD access
        is performed for any of them (ESC4 and the NTAuth/AIA/Root sweep
        gained snapshot support in v1.19.1; a snapshot collected with an
        older module version won't have the NTAuth/AIA/Root fields, in
        which case that one sweep is skipped with a note rather than
        erroring). ESC8 (a live HTTP probe against the CA host itself) has
        no possible snapshot representation and is always skipped entirely
        under -Snapshot, consistent with Test-ADCoercionAndRelayExposure.
    .OUTPUTS
        [ADSecurityFinding[]]
    #>
    [CmdletBinding()]
    param(
        [Parameter()]
        [hashtable]$Snapshot
    )

    Write-Verbose "Starting AD CS extended security audit (ESC4/ESC8/ROCA/weak crypto)..."
    $findings = @()

    $lowPrivilegedPrincipals = @(
        'Authenticated Users'
        'Domain Users'
        'Domain Computers'
        'Everyone'
    )

    $trustedAclPrincipals = @(
        'Domain Admins'
        'Enterprise Admins'
        'Administrators'
        'SYSTEM'
        'Cert Publishers'
        'Enterprise Read-only Domain Controllers'
    )

    $certTemplates = @()
    $certAuthorities = @()
    $adcsInstalled = $false
    $configContext = $null

    if ($Snapshot) {
        if ($Snapshot.ContainsKey('ADCS') -and $Snapshot.ADCS.Installed) {
            Write-Verbose "Test-ADCSExtended: using snapshot AD CS inventory."
            $adcsInstalled = $true
            $certTemplates = @($Snapshot.ADCS.CertificateTemplates)
            $certAuthorities = @($Snapshot.ADCS.CertificateAuthorities)
        }
        else {
            Write-Verbose "Test-ADCSExtended: snapshot indicates AD CS is not installed; no findings."
            return $findings
        }
    }
    else {
        try {
            $__adServer = Get-ADSecurityAuditTargetServerValue
            $configContext = Get-ADRootDSEValue -Property configurationNamingContext -Server $__adServer
            $pkiContainer = "CN=Public Key Services,CN=Services,$configContext"

            # -SearchScope OneLevel, not the default Subtree: a Subtree
            # search over "CN=Certificate Templates,..."/"CN=Enrollment
            # Services,..." returns the CONTAINER OBJECT ITSELF alongside
            # its real children (pKICertificateTemplate/pKIEnrollmentService
            # objects, which are never nested further than one level under
            # these containers). Neither loop below filtered by objectClass,
            # so that container object was silently iterated as if it were
            # a real template/CA - its own Name IS literally "Certificate
            # Templates"/"Enrollment Services", it has no dNSHostName or
            # cACertificate, and every check against it either produced
            # confusing noise (e.g. "CA 'Enrollment Services' has no
            # dNSHostName; skipping ESC8 probe" - about the container, not
            # any real, misconfigured CA) or was silently skipped. OneLevel
            # returns only the real child objects, never the base container.
            $certTemplates = @(Invoke-ADQueryWithRetry -OperationName 'Get certificate templates (ADCS extended audit)' -Query {
                Get-ADObject -SearchBase "CN=Certificate Templates,$pkiContainer" -SearchScope OneLevel -Filter * -Properties * -Server $__adServer -ErrorAction Stop
            })
            $adcsInstalled = $true

            try {
                $certAuthorities = @(Invoke-ADQueryWithRetry -OperationName 'Get enrollment services (ADCS extended audit)' -Query {
                    Get-ADObject -SearchBase "CN=Enrollment Services,$pkiContainer" -SearchScope OneLevel -Filter * -Properties * -Server $__adServer -ErrorAction Stop
                })
            }
            catch {
                Write-Verbose "Test-ADCSExtended: could not enumerate Certificate Authorities: $_"
            }
        }
        catch {
            Write-Verbose "Test-ADCSExtended: AD Certificate Services not found or accessible. Skipping AD CS extended audit."
            return $findings
        }
    }

    if (-not $certTemplates -or $certTemplates.Count -eq 0) {
        Write-Verbose "Test-ADCSExtended: no certificate templates found; skipping template-based checks."
    }

    # -------------------------------------------------------------------
    # ESC4: dangerous template ACLs
    # -------------------------------------------------------------------
    # Fixed in v1.19.1: this was documented as "live only - not captured in
    # snapshot" and skipped entirely under -Snapshot, but Get-ADSnapshot has
    # collected a flattened per-template Access ACL since v1.19.0 (added for
    # Test-ADCertificateServices' ESC7 check) - the same data this check
    # needs was already sitting in the snapshot, just never wired up here.
    # Offline path below reads $template.Access (already-flattened ACEs,
    # IdentityReference as a plain string) instead of a live Get-Acl call;
    # detection logic is otherwise identical to the live path.
    foreach ($template in $certTemplates) {
        $templateName = if ($template.displayName) { $template.displayName } else { $template.Name }

        $templateAces = if ($Snapshot) { @($template.Access) } else {
            try {
                # Get-ADObject -Properties nTSecurityDescriptor, not
                # Get-Acl -Path "AD:..." - the latter has no -Server
                # parameter and reads via the AD: PSDrive's ambient
                # default domain/DC, bypassing this module's -Server
                # override entirely. nTSecurityDescriptor returns the
                # same ActiveDirectorySecurity object (.Access, etc.) via
                # a real, -Server-aware Get-AD* cmdlet.
                @((Get-ADObject -Identity $template.DistinguishedName -Properties nTSecurityDescriptor -Server $__adServer -ErrorAction Stop).nTSecurityDescriptor.Access)
            }
            catch {
                Write-Verbose "Test-ADCSExtended: could not get ACL for template '$templateName': $_"
                @()
            }
        }

        $dangerousAces = @()
        foreach ($ace in $templateAces) {
            $principal = if ($Snapshot) { $ace.IdentityReference } else { $ace.IdentityReference.Value }
            $isLowPriv = $false
            foreach ($lowPriv in $lowPrivilegedPrincipals) {
                if ($principal -match [regex]::Escape($lowPriv)) { $isLowPriv = $true; break }
            }
            if (-not $isLowPriv) { continue }

            $isTrusted = $false
            foreach ($trusted in $trustedAclPrincipals) {
                if ($principal -match [regex]::Escape($trusted)) { $isTrusted = $true; break }
            }
            if ($isTrusted) { continue }

            foreach ($right in $Script:DangerousStandardRights) {
                if ($ace.ActiveDirectoryRights -match $right) {
                    $dangerousAces += "$principal ($($ace.ActiveDirectoryRights))"
                    break
                }
            }
        }

        if ($dangerousAces.Count -gt 0) {
            $finding = [ADSecurityFinding]::new()
            $finding.Category = 'Certificate Services'
            $finding.Issue = 'Certificate Template with Weak ACL (ESC4)'
            $finding.Severity = 'High'
            $finding.SeverityLevel = 3
            $finding.AffectedObject = $templateName
            # BUGFIX: was a single semicolon-joined run-on sentence; rendered
            # as one bullet per ACE instead for readability once there's more
            # than a couple of principals.
            $dangerousAceBullets = ($dangerousAces | ForEach-Object { "- $_" }) -join "`n"
            $finding.Description = "Certificate template '$templateName' grants Write/WriteDacl/WriteOwner/GenericAll/GenericWrite rights to low-privileged principal(s):`n$dangerousAceBullets"
            $finding.Impact = "A principal with write access to a certificate template can reconfigure it into an ESC1-style template (enable SAN, remove approval, weaken EKUs) and then enroll for a certificate impersonating any account, including Domain Admins."
            $finding.Remediation = "Remove Write/WriteDacl/WriteOwner/GenericAll/GenericWrite permissions on the template from any principal other than PKI/Domain administrators."
            $finding.EstimatedEffort = 'Medium - a single-template ACE removal, but confirm the trustee isn''t a legitimate certificate-lifecycle-management tool or service account before removing.'
            $finding.KnownRisks = 'Procedural - confirm the trustee isn''t an active cert-management automation account before removing; no realistic legitimate technical break otherwise.'
            $finding.BackupRollback = 'Moderate - export the template''s ACL (certutil -v -template or PSPKI) before changing it so the exact ACE can be restored if needed.'
            $finding.Details = @{
                DistinguishedName = $template.DistinguishedName
                DangerousAces     = $dangerousAces -join '; '
                ESCType           = 'ESC4'
            }
            $findings += $finding
        }
    }

    # -------------------------------------------------------------------
    # High-risk-without-approval check (snapshot-aware; attribute-only)
    # Deliberately distinct from ESC1 (SAN + low-priv enrollment) and ESC2
    # (no EKU / Any-Purpose): this flags the absence of the manager
    # approval gate on templates carrying either risky property.
    # -------------------------------------------------------------------
    foreach ($template in $certTemplates) {
        $templateName = if ($template.displayName) { $template.displayName } else { $template.Name }

        $certNameFlag = $template.'msPKI-Certificate-Name-Flag'
        $enrollmentFlag = $template.'msPKI-Enrollment-Flag'
        $ekus = $template.'msPKI-Certificate-Application-Policy'
        $ekusV1 = $template.'pKIExtendedKeyUsage'

        $allowsSan = [bool]([int64]($certNameFlag) -band 1)                        # CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT
        $anyPurpose = ($ekus -contains '2.5.29.37.0') -or ($ekusV1 -contains '2.5.29.37.0')
        $requiresApproval = [bool]([int64]($enrollmentFlag) -band 2)               # CT_FLAG_PEND_ALL_REQUESTS

        if (($allowsSan -or $anyPurpose) -and -not $requiresApproval) {
            $finding = [ADSecurityFinding]::new()
            $finding.Category = 'Certificate Services'
            $finding.Issue = 'Certificate Template Allows High-Risk Enrollment Without Manager Approval'
            $finding.Severity = 'High'
            $finding.SeverityLevel = 3
            $finding.AffectedObject = $templateName
            $finding.Description = "Certificate template '$templateName' allows $(if ($allowsSan) { 'enrollee-supplied subject/SAN' }) $(if ($allowsSan -and $anyPurpose) { 'and' }) $(if ($anyPurpose) { 'an Any-Purpose EKU' }) without requiring CA manager approval (CT_FLAG_PEND_ALL_REQUESTS is not set)."
            $finding.Impact = "Certificates matching this template are issued automatically with no human review, removing a compensating control that would otherwise catch abuse of the risky template properties."
            $finding.Remediation = "Require manager approval for this template (set CT_FLAG_PEND_ALL_REQUESTS) until the SAN/Any-Purpose properties can be removed or enrollment can be restricted."
            $finding.EstimatedEffort = 'Low - toggling the "CA certificate manager approval" flag on one template.'
            $finding.KnownRisks = 'Enabling manager approval adds a manual approval step that will delay or block any automated enrollment workflow (autoenrollment, ACME-style automated issuance) that currently assumes instant issuance.'
            $finding.BackupRollback = 'Easy - untick the approval requirement; effective immediately for new requests, no data loss.'
            $finding.Details = @{
                DistinguishedName = $template.DistinguishedName
                AllowsSan         = $allowsSan
                AnyPurposeEku     = $anyPurpose
                RequiresApproval  = $requiresApproval
            }
            $findings += $finding
        }
    }

    # -------------------------------------------------------------------
    # ESC8: CA web enrollment over HTTP without EPA (live only)
    # -------------------------------------------------------------------
    if ($Snapshot) {
        Write-Verbose "Test-ADCSExtended: -Snapshot supplied; skipping live ESC8 web-enrollment probe (offline mode performs no live AD/network access)."
        Add-ADOfflineSkipNote -Test 'ADCSExtended' -Check 'ESC8: CA web enrollment over HTTP without EPA' `
            -Reason 'This is a live HTTP probe against the CA host itself, not an AD attribute - there is no snapshot representation possible. Run this check live (without -Snapshot) if you need this coverage.'
    }
    else {
        foreach ($ca in $certAuthorities) {
            $caName = $ca.Name
            $caHost = $ca.dNSHostName
            if (-not $caHost) {
                Write-Verbose "Test-ADCSExtended: CA '$caName' has no dNSHostName; skipping ESC8 probe."
                continue
            }

            try {
                $webEnrollState = Invoke-ADQueryWithRetry -OperationName "Probe CA web enrollment on $caHost" -Query {
                    Invoke-Command -ComputerName $caHost -ErrorAction Stop -ScriptBlock {
                        $result = [PSCustomObject]@{
                            CertSrvVDirPresent = $false
                            EpaRequired        = $null
                            Error              = $null
                        }
                        try {
                            Import-Module WebAdministration -ErrorAction Stop
                            $vdir = Get-WebApplication -Site 'Default Web Site' -Name 'CertSrv' -ErrorAction SilentlyContinue
                            if ($vdir) {
                                $result.CertSrvVDirPresent = $true
                                try {
                                    $epa = Get-WebConfigurationProperty -PSPath 'IIS:\Sites\Default Web Site\CertSrv' `
                                        -Filter 'system.webServer/security/authentication/windowsAuthentication' `
                                        -Name 'extendedProtection.tokenChecking' -ErrorAction Stop
                                    $result.EpaRequired = ($epa.Value -eq 'Require')
                                }
                                catch {
                                    $result.EpaRequired = $null
                                }
                            }
                        }
                        catch {
                            $result.Error = "$_"
                        }
                        return $result
                    }
                }
            }
            catch {
                Write-Verbose "Test-ADCSExtended: could not probe CA host '$caHost' for web enrollment state: $_"
                $webEnrollState = $null
            }

            if ($webEnrollState -and $webEnrollState.CertSrvVDirPresent) {
                $epaMissing = ($webEnrollState.EpaRequired -ne $true)
                if ($epaMissing) {
                    $finding = [ADSecurityFinding]::new()
                    $finding.Category = 'Certificate Services'
                    $finding.Issue = 'CA Web Enrollment over HTTP (ESC8)'
                    $finding.Severity = 'Critical'
                    $finding.SeverityLevel = 4
                    $finding.AffectedObject = $caName
                    $finding.Description = "Certificate Authority '$caName' ($caHost) has the CertSrv web enrollment endpoint installed without Extended Protection for Authentication (EPA) enforced."
                    $finding.Impact = "An attacker who coerces a privileged host (e.g. a Domain Controller) to authenticate to them can relay that NTLM authentication to the CA's HTTP enrollment endpoint and obtain a certificate as that host/account, leading to domain compromise."
                    $finding.Remediation = "Disable HTTP(S) web enrollment if unused, or require Extended Protection for Authentication ('Require') on the CertSrv virtual directory and enforce HTTPS with channel binding."
                    $finding.EstimatedEffort = 'Medium - requires enabling HTTPS web enrollment (certificate + IIS binding) and usually coordination with whoever manages the CA''s IIS instance; confirm no client submits enrollment requests over plain HTTP first.'
                    $finding.KnownRisks = 'Enforcing HTTPS-only web enrollment can break legacy clients or scripts that submit requests over plain HTTP until they''re updated to the HTTPS endpoint.'
                    $finding.BackupRollback = 'Moderate - revert the IIS binding/auth settings and re-enable the HTTP endpoint if needed; requires an IIS restart but no data loss.'
                    $finding.OperationalNotes = 'HTTPS alone doesn''t fully close ESC8''s NTLM relay risk without Extended Protection for Authentication (EPA) also enabled - consider enabling EPA on the enrollment endpoint at the same time.'
                    $finding.Details = @{
                        DistinguishedName = $ca.DistinguishedName
                        CAHost            = $caHost
                        EpaRequired       = $webEnrollState.EpaRequired
                        ESCType           = 'ESC8'
                    }
                    $findings += $finding
                }
            }
            elseif ($webEnrollState -and $webEnrollState.Error) {
                Write-Verbose "Test-ADCSExtended: web enrollment probe on '$caHost' reported: $($webEnrollState.Error)"
            }
        }
    }

    # -------------------------------------------------------------------
    # ROCA / weak signature sweep of the CA's own certificate(s)
    # (snapshot-aware: uses cACertificate already captured on CA objects).
    # -------------------------------------------------------------------
    $weakCertResults = [System.Collections.ArrayList]::new()

    foreach ($ca in $certAuthorities) {
        foreach ($b in @($ca.'cACertificate')) {
            if (-not $b) { continue }
            $result = Test-ADCSWeakCertificate -Bytes $b -Source "CA:$($ca.Name)"
            if ($result) { [void]$weakCertResults.Add($result) }
        }
    }

    # -------------------------------------------------------------------
    # NTAuth / AIA / Root store sweep
    # -------------------------------------------------------------------
    # Fixed in v1.19.1: this was documented as "live only - not captured in
    # snapshot" and skipped entirely under -Snapshot, but Get-ADSnapshot now
    # collects these same cACertificate blobs (same data shape/risk profile
    # as the CA objects' cACertificate, already in the snapshot since
    # v1.19.0) - so this can run fully offline too.
    if ($Snapshot) {
        if ($Snapshot.ADCS.ContainsKey('NTAuthCertificates')) {
            foreach ($blob in @($Snapshot.ADCS.NTAuthCertificates)) {
                $result = Test-ADCSWeakCertificate -Bytes $blob.Bytes -Source "NTAuth`:$($blob.Source)"
                if ($result) { [void]$weakCertResults.Add($result) }
            }
            foreach ($blob in @($Snapshot.ADCS.AIACertificates)) {
                $result = Test-ADCSWeakCertificate -Bytes $blob.Bytes -Source "AIA`:$($blob.Source)"
                if ($result) { [void]$weakCertResults.Add($result) }
            }
            foreach ($blob in @($Snapshot.ADCS.RootCACertificates)) {
                $result = Test-ADCSWeakCertificate -Bytes $blob.Bytes -Source "Root`:$($blob.Source)"
                if ($result) { [void]$weakCertResults.Add($result) }
            }
        }
        else {
            Write-Verbose "Test-ADCSExtended: snapshot predates v1.19.1's NTAuth/AIA/Root collection; skipping that sweep for this older snapshot."
            Add-ADOfflineSkipNote -Test 'ADCSExtended' -Check 'NTAuth/AIA/Root store weak-signature sweep' `
                -Reason 'This snapshot was collected with a version older than v1.19.1 and does not contain NTAuth/AIA/Root certificate data. Re-collect the snapshot with the current module version for this coverage.'
        }
    }
    else {
        try {
            $pkiContainer = "CN=Public Key Services,CN=Services,$configContext"
            $storeTargets = @{
                'NTAuth' = "CN=NTAuthCertificates,$pkiContainer"
                'AIA'    = "CN=AIA,$pkiContainer"
                'Root'   = "CN=Certification Authorities,$pkiContainer"
            }

            foreach ($storeName in $storeTargets.Keys) {
                $blobs = Get-ADCSCertificateBlob -ContainerDN $storeTargets[$storeName] -Server $__adServer
                foreach ($blob in $blobs) {
                    $result = Test-ADCSWeakCertificate -Bytes $blob.Bytes -Source "$storeName`:$($blob.Source)"
                    if ($result) { [void]$weakCertResults.Add($result) }
                }
            }
        }
        catch {
            Write-Verbose "Test-ADCSExtended: could not sweep NTAuth/AIA/Root store: $_"
        }
    }

    foreach ($weak in $weakCertResults) {
        if ($weak.RocaCandidate) {
            $finding = [ADSecurityFinding]::new()
            $finding.Category = 'Certificate Services'
            $finding.Issue = 'ROCA-Vulnerable Certificate Key'
            $finding.Severity = 'High'
            $finding.SeverityLevel = 3
            $finding.AffectedObject = $weak.Source
            $finding.Description = "Certificate '$($weak.Subject)' (thumbprint $($weak.Thumbprint)) from $($weak.Source) matches the ROCA (CVE-2017-15361) weak-key fingerprint for RSA keys generated by the affected Infineon RSALib."
            $finding.Impact = "ROCA-vulnerable RSA keys can, with sufficient compute, have their private key factored from the public key alone, fully compromising anything the certificate protects or authenticates."
            $finding.Remediation = "Confirm with a dedicated ROCA-detection tool, then revoke and reissue the certificate with a key generated by an unaffected library."
            $finding.EstimatedEffort = 'High - revoking and reissuing a certificate requires coordinating with every consumer of that certificate, since revocation invalidates trust immediately and may need a maintenance window if the certificate is in active use (e.g. smart card logon, TLS).'
            $finding.KnownRisks = 'ROCA-vulnerable RSA keys can, with sufficient compute, have their private key factored from the public key alone (CVE-2017-15361), so this is a confirmed, documented weakness, not a hypothetical one; revoking the certificate breaks authentication/encryption for everything relying on it until the replacement is deployed.'
            $finding.BackupRollback = 'Hard/Limited - a revoked certificate cannot be un-revoked; the only path forward is issuing a new one with a key from an unaffected library, so keep the old certificate available read-only for verifying historically-signed artifacts if that''s needed.'
            $finding.Details = @{
                Source             = $weak.Source
                Subject            = $weak.Subject
                Thumbprint         = $weak.Thumbprint
                KeySize            = $weak.KeySize
                SignatureAlgorithm = $weak.SignatureAlgorithm
                Note               = 'Probabilistic fingerprint test; confirm before remediation.'
            }
            $findings += $finding
        }

        if ($weak.WeakSignature -or $weak.WeakModulus) {
            $reasons = @()
            if ($weak.WeakSignature) { $reasons += "weak signature algorithm ($($weak.SignatureAlgorithm))" }
            if ($weak.WeakModulus) { $reasons += "RSA key size below 2048 bits ($($weak.KeySize) bits)" }

            $finding = [ADSecurityFinding]::new()
            $finding.Category = 'Certificate Services'
            $finding.Issue = 'Weak Signature Algorithm in PKI Trust Store'
            $finding.Severity = 'Medium'
            $finding.SeverityLevel = 2
            $finding.AffectedObject = $weak.Source
            $finding.Description = "Certificate '$($weak.Subject)' (thumbprint $($weak.Thumbprint)) from $($weak.Source) has $($reasons -join ' and ')."
            $finding.Impact = "Weak signature algorithms (MD2/MD4/MD5/SHA0/SHA1) or undersized RSA keys undermine the integrity of the certificate chain and any trust decisions made against it."
            $finding.Remediation = "Reissue the certificate with SHA-256 (or better) and an RSA key of at least 2048 bits (3072+ recommended for CA certificates)."
            $finding.EstimatedEffort = 'Medium - reissuing affected certificates with a stronger signature algorithm (e.g. SHA-256+) and coordinating with every consumer of the old chain.'
            $finding.KnownRisks = 'Modern OSes and browsers already reject SHA-1-signed certificates, but legacy embedded devices or older client OSes may only trust the SHA-1 chain and could lose connectivity until they''re updated to trust the new one.'
            $finding.BackupRollback = 'Hard/Limited - like other certificate revocation/reissuance, this isn''t reversible to the old certificate''s validity; keep the old CA certificate available for verifying already-issued signatures if needed.'
            $finding.Details = @{
                Source             = $weak.Source
                Subject            = $weak.Subject
                Thumbprint         = $weak.Thumbprint
                KeySize            = $weak.KeySize
                SignatureAlgorithm = $weak.SignatureAlgorithm
                NotAfter           = $weak.NotAfter
            }
            $findings += $finding
        }
    }

    Write-Verbose "AD CS extended audit complete. Found $($findings.Count) issues."
    return $findings
}

#endregion

#region CA Chase-Fallback Exposure (CVE-2026-54121 / "Certighost")

function Test-ADCSChaseFallback {
    <#
    .SYNOPSIS
        Detects Enterprise CAs with the EDITF_ENABLECHASECLIENTDC policy
        flag set, the configuration condition CVE-2026-54121 ("Certighost")
        abuses to obtain a certificate asserting a Domain Controller's
        identity from a low-privileged, attacker-controlled account.
    .DESCRIPTION
        Reads each discovered Enterprise CA's policy\EditFlags registry
        value (same registry key family as the CA policy-module settings
        this module already reads) and checks the EDITF_ENABLECHASECLIENTDC
        bit (0x00100000). When set, the CA honors a requester-supplied
        client-DC ("cdc") hint during certificate-request identity
        resolution; on an unpatched CA this hint is used without
        confirming it actually resolves to a genuine DC object, letting an
        attacker point the CA at a host they control and obtain a
        certificate asserting a DC's identity, enabling DC impersonation
        and DCSync-class domain compromise.

        This is a configuration exposure check, not a patch-level check:
        the flag is the exposure indicator regardless of whether the CA
        host has installed Microsoft's July 14, 2026 security update
        (which validates the chase target before contacting it, but does
        not clear the flag). A patched CA with the flag still set remains
        configured in the historically risky state and is still flagged
        here, as defense-in-depth - the flag can be re-enabled later via
        policy, imaging, or an admin action independent of patch state.

        Detection only: reads one registry value per discovered CA. No
        certificate requests, no PoC/exploitation traffic, no coercion.
    .PARAMETER Snapshot
        Optional snapshot hashtable (from Get-ADSnapshot). This check has
        no snapshot representation - policy\EditFlags is a registry value
        on the CA host itself, not an AD attribute - so it is always
        skipped under -Snapshot, consistent with this module's other
        live-only CA-host probe (ESC8 in Test-ADCSExtended).
    .OUTPUTS
        [ADSecurityFinding[]]
    #>
    [CmdletBinding()]
    param(
        [Parameter()]
        [hashtable]$Snapshot
    )

    Write-Verbose "Starting AD CS chase-fallback exposure audit (CVE-2026-54121 / Certighost)..."
    $findings = @()

    # Bit value confirmed against independent public technical write-ups of
    # CVE-2026-54121 (0x00100000 / 1048576) - not redefined ad hoc elsewhere
    # in this module, since no existing EDITF_* constant was already defined
    # here to reuse.
    $editfEnableChaseClientDc = 0x00100000

    $certAuthorities = @()
    $adcsInstalled = $false

    if ($Snapshot) {
        if ($Snapshot.ContainsKey('ADCS') -and $Snapshot.ADCS.Installed) {
            $adcsInstalled = $true
            $certAuthorities = @($Snapshot.ADCS.CertificateAuthorities)
        }
        else {
            Write-Verbose "Test-ADCSChaseFallback: snapshot indicates AD CS is not installed; no findings."
            return $findings
        }

        Write-Verbose "Test-ADCSChaseFallback: -Snapshot supplied; skipping live registry probe (offline mode performs no live AD/network access)."
        Add-ADOfflineSkipNote -Test 'ADCSChaseFallback' -Check 'EDITF_ENABLECHASECLIENTDC / Certighost (CVE-2026-54121) exposure' `
            -Reason 'This is a live registry probe against the CA host itself (policy\EditFlags), not an AD attribute - there is no snapshot representation possible. Run this check live (without -Snapshot) if you need this coverage.'
        return $findings
    }

    try {
        $__adServer = Get-ADSecurityAuditTargetServerValue
        $configContext = Get-ADRootDSEValue -Property configurationNamingContext -Server $__adServer
        $pkiContainer = "CN=Public Key Services,CN=Services,$configContext"

        $certAuthorities = @(Invoke-ADQueryWithRetry -OperationName 'Get enrollment services (ADCS chase-fallback audit)' -Query {
            Get-ADObject -SearchBase "CN=Enrollment Services,$pkiContainer" -SearchScope OneLevel -Filter * -Properties dNSHostName -Server $__adServer -ErrorAction Stop
        })
        $adcsInstalled = $true
    }
    catch {
        Write-Verbose "Test-ADCSChaseFallback: AD Certificate Services not found or accessible. Skipping chase-fallback audit."
        return $findings
    }

    if (-not $adcsInstalled -or -not $certAuthorities -or @($certAuthorities).Count -eq 0) {
        Write-Verbose "Test-ADCSChaseFallback: no Enterprise CAs discovered; skipping."
        return $findings
    }

    foreach ($ca in $certAuthorities) {
        $caName = $ca.Name
        $caHost = $ca.dNSHostName
        if (-not $caHost) {
            Write-Verbose "Test-ADCSChaseFallback: CA '$caName' has no dNSHostName; skipping."
            continue
        }

        try {
            $editFlagsResult = Invoke-ADQueryWithRetry -OperationName "Read policy\EditFlags on $caHost" -Query {
                Invoke-Command -ComputerName $caHost -ErrorAction Stop -ScriptBlock {
                    param($CaSanitizedName)
                    $result = [PSCustomObject]@{
                        EditFlagsRead = $false
                        EditFlags     = $null
                        Error         = $null
                    }
                    try {
                        # Same registry family as this module's other CA
                        # policy-module reads:
                        # HKLM\SYSTEM\CurrentControlSet\Services\CertSvc\Configuration\<CA
                        # sanitized name>\PolicyModules\CertificateAuthority_MicrosoftDefault.Policy
                        #
                        # A CA's registry key name (its "sanitized name") can
                        # differ from its AD common name if the CN contains
                        # characters not valid in a registry key. Prefer an
                        # exact match against the AD-supplied name first;
                        # fall back to the sole child key when there's only
                        # one CA configured on the host (by far the common
                        # case), and otherwise report ambiguity rather than
                        # silently guessing which CA's flags we're reading.
                        $caRegNames = @(Get-ChildItem 'HKLM:\SYSTEM\CurrentControlSet\Services\CertSvc\Configuration' -ErrorAction Stop | Select-Object -ExpandProperty PSChildName)
                        $matchedRegCaName = $null
                        if ($caRegNames -contains $CaSanitizedName) {
                            $matchedRegCaName = $CaSanitizedName
                        }
                        elseif (@($caRegNames).Count -eq 1) {
                            $matchedRegCaName = $caRegNames[0]
                        }

                        if ($matchedRegCaName) {
                            $policyPath = "HKLM:\SYSTEM\CurrentControlSet\Services\CertSvc\Configuration\$matchedRegCaName\PolicyModules\CertificateAuthority_MicrosoftDefault.Policy"
                            if (Test-Path $policyPath) {
                                $prop = Get-ItemProperty -Path $policyPath -Name 'EditFlags' -ErrorAction Stop
                                $result.EditFlagsRead = $true
                                $result.EditFlags = [int]$prop.EditFlags
                            }
                            else {
                                $result.Error = "Policy module registry key not found under CA '$matchedRegCaName'."
                            }
                        }
                        else {
                            $result.Error = "Could not unambiguously match AD CA name '$CaSanitizedName' to a registry CA key; found: $($caRegNames -join ', ')."
                        }
                    }
                    catch {
                        $result.Error = "$_"
                    }
                    return $result
                } -ArgumentList $caName
            }
        }
        catch {
            Write-Verbose "Test-ADCSChaseFallback: could not read policy\EditFlags on CA host '$caHost': $_"
            $editFlagsResult = $null
        }

        if (-not $editFlagsResult -or -not $editFlagsResult.EditFlagsRead) {
            if ($editFlagsResult -and $editFlagsResult.Error) {
                Write-Verbose "Test-ADCSChaseFallback: EditFlags probe on '$caHost' reported: $($editFlagsResult.Error)"
            }
            continue
        }

        $chaseFallbackEnabled = (($editFlagsResult.EditFlags -band $editfEnableChaseClientDc) -ne 0)

        if ($chaseFallbackEnabled) {
            $finding = [ADSecurityFinding]::new()
            $finding.Category = 'Certificate Services'
            $finding.Issue = 'CA Chase-Fallback Enabled (CVE-2026-54121 / Certighost Exposure)'
            $finding.Severity = 'Critical'
            $finding.SeverityLevel = 4
            $finding.AffectedObject = "$caName ($caHost)"
            $finding.Description = "Certificate Authority '$caName' ($caHost) has the EDITF_ENABLECHASECLIENTDC policy flag set on its policy\EditFlags registry value. This enables the CA's client-DC 'chase' fallback, in which the CA will contact a requester-supplied host to resolve identity data during certificate issuance."
            $finding.Impact = "CVE-2026-54121 (`"Certighost`", CVSS 8.8) abuses this chase-fallback behavior: an authenticated, low-privileged attacker with network access to the CA can supply a client-DC hint pointing at an attacker-controlled host, causing the CA to obtain and use that host's identity data when issuing a certificate. On an unpatched CA this can result in a certificate asserting a Domain Controller's identity being issued to the attacker, enabling DC impersonation and DCSync-class full domain compromise. The flag is the exposure indicator independent of the CA's patch level: Microsoft's July 14, 2026 update adds chase-target validation but does not clear this flag, so a patched CA with the flag still set remains configured in the historically risky state and can become exploitable again if the flag is re-enabled by policy, imaging, or later admin action."
            $finding.Remediation = "Apply Microsoft's July 14, 2026 security update for CVE-2026-54121, which adds chase-target validation to the CA. Independently, clear the flag as defense-in-depth (or as an immediate stopgap if the update cannot be applied yet): certutil -config `"$caName`" -setreg policy\EditFlags -EDITF_ENABLECHASECLIENTDC, then restart Certificate Services (Restart-Service CertSvc -Force). Test in staging first if cross-domain/cross-forest enrollment relies on the chase fallback, since disabling it will break that use case until the CA can reach the relevant DCs directly."
            $finding.EstimatedEffort = 'High - before disabling the flag or patching, requires discovering which cross-domain/cross-forest enrollment workflows (if any) depend on the chase fallback across every CA, since Microsoft''s own advisory notes the registry mitigation was validated only in a lab and should be tested per-CA before production rollout.'
            $finding.KnownRisks = 'Clearing the flag (or the patch''s added validation) can break certificate enrollment for legitimate cross-domain or cross-forest clients that rely on the CA''s chase behavior to resolve a client-DC hint the CA cannot otherwise reach directly.'
            $finding.BackupRollback = 'Easy - the change is a single registry value; if a legitimate enrollment workflow breaks, re-enable EDITF_ENABLECHASECLIENTDC via certutil and restart CertSvc to restore the prior behavior immediately, with no data loss.'
            $finding.OperationalNotes = 'Re-enabling the flag as a rollback restores the CVE-2026-54121 exposure, so treat it as strictly temporary and monitor Certificate Services event ID 4886 (a cert request carrying a client-DC hint that doesn''t match a known DC) while investigating any dependency.'
            $finding.Details = @{
                DistinguishedName = $ca.DistinguishedName
                CAHost            = $caHost
                EditFlags         = ('0x{0:X}' -f $editFlagsResult.EditFlags)
                EditFlagBit       = 'EDITF_ENABLECHASECLIENTDC (0x00100000)'
                CVE               = 'CVE-2026-54121'
                PatchDate         = '2026-07-14'
            }
            $findings += $finding
        }
    }

    Write-Verbose "AD CS chase-fallback exposure audit complete. Found $($findings.Count) issues."
    return $findings
}

#endregion
