#region Certificate Services Extended Audits (ESC4, ESC8, ROCA, weak PKI crypto)
#
# Extends src/CertificateServicesAudits.ps1 (ESC1/ESC2/ESC3/ESC7) with the
# remaining PingCastle-comparable AD CS checks:
#
#   - ESC4  : dangerous ACLs on certificate templates (Write/WriteDacl/
#             WriteOwner/GenericAll/GenericWrite granted to low-privileged
#             principals), which let an attacker rewrite a template into an
#             ESC1-style template.
#   - ESC8  : CA web enrollment reachable over HTTP without Extended
#             Protection for Authentication (EPA), enabling NTLM relay to
#             the enrollment endpoint.
#   - A high-risk-without-approval check that flags templates combining
#     enrollee-supplied subject/SAN or an Any-Purpose EKU with no manager
#     approval gate (CT_FLAG_PEND_ALL_REQUESTS unset). This is deliberately
#     scoped differently from the existing ESC1 (SAN + low-priv enrollment)
#     and ESC2 (no EKU / Any-Purpose) checks so it does not duplicate them.
#   - ROCA-vulnerable keys (CVE-2017-15361) and weak signature algorithms /
#     RSA moduli across the CA certificates, NTAuth store, and AIA/Root
#     store published in the Configuration partition.
#
# PingCastle-comparable check(s): A-CertEnrollHttp, A-CertTempNoSecurity,
# A-CertTempAnyPurpose, A-CertTempAnyone, A-CertTempCustomSubject,
# A-CertROCA, A-CertWeakRsaComponent, A-MD5RootCert, A-SHA1RootCert.
#
# DETECTION ONLY: every check here reads AD attributes/ACLs, certificate
# bytes already published in AD, or (for ESC8 only) remote service/registry
# state on the CA host itself. Nothing here requests, forges, or relays a
# certificate, and no coercion/PoC traffic is sent to any host.
#
# Snapshot contract: certificate template/CA enumeration and the
# attribute-only checks (approval-gate check, and weak-signature/ROCA
# evaluation of the CA's own published certificate) are snapshot-aware via
# Snapshot.ADCS (from Get-ADSnapshot, unchanged schema). ESC4 (per-template
# ACL), ESC8 (live network probe of the CA host), and the NTAuth/AIA/Root
# store sweep are live AD/network reads with no snapshot representation, so
# - consistent with the anonymous-bind probe in Test-ADDomainHardeningFlags
# and the per-DC probes in Test-ADCoercionAndRelayExposure - they are
# skipped entirely when this function is invoked with -Snapshot.

# Small set of primes (with a fast brute-force order computation, valid
# since each prime here is tiny) used for a probabilistic ROCA fingerprint
# test. A modulus is treated as a ROCA candidate only when the discrete-log
# style test below holds for every one of these primes; this mirrors the
# public description of the ROCA (CVE-2017-15361) fingerprinting technique
# but is a heuristic re-implementation, not a copy of any vendor/tool code.
$Script:ADCSRocaTestPrimes = @(3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,101,103,107,109,113)

function ConvertTo-ADCSBigInteger {
    <#
    .SYNOPSIS
        Converts a big-endian unsigned byte array (as returned by
        RSAParameters.Modulus) into a positive [System.Numerics.BigInteger].
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [byte[]]$BigEndianBytes
    )

    $little = [byte[]]$BigEndianBytes.Clone()
    [Array]::Reverse($little)
    # Append a trailing zero byte so BigInteger (which is little-endian,
    # two's-complement) never interprets the value as negative.
    $withSign = New-Object byte[] ($little.Length + 1)
    [Array]::Copy($little, $withSign, $little.Length)
    return [System.Numerics.BigInteger]::new($withSign)
}

function Test-ADCSRocaFingerprint {
    <#
    .SYNOPSIS
        Heuristic ROCA (CVE-2017-15361) fingerprint test for an RSA modulus.
    .DESCRIPTION
        For each small prime p in $Script:ADCSRocaTestPrimes, computes the
        multiplicative order of 65537 mod p, then checks whether
        (N mod p) raised to that order is congruent to 1 mod p - the
        signature of a modulus generated by the affected Infineon RSALib
        key-generation routine. Flags the modulus only when the test holds
        for every prime evaluated. This is a probabilistic filter (as the
        public description of ROCA detection is), not a certainty; genuine
        candidates should be confirmed with a dedicated ROCA-detection tool
        before remediation is prioritised.
    .OUTPUTS
        [bool]
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [System.Numerics.BigInteger]$Modulus
    )

    $tested = 0
    $matched = 0

    foreach ($p in $Script:ADCSRocaTestPrimes) {
        $pBig = [System.Numerics.BigInteger]$p
        $g = [System.Numerics.BigInteger]65537 % $pBig
        if ($g -eq [System.Numerics.BigInteger]0) { continue }

        # Brute-force multiplicative order of g mod p (p is tiny, so this
        # is at most p-1 iterations).
        $order = 1
        $val = $g
        while ($val -ne [System.Numerics.BigInteger]1 -and $order -le $p) {
            $val = ($val * $g) % $pBig
            $order++
        }

        $nModP = $Modulus % $pBig
        if ($nModP -eq [System.Numerics.BigInteger]0) { continue }

        $tested++
        $result = [System.Numerics.BigInteger]::ModPow($nModP, $order, $pBig)
        if ($result -eq [System.Numerics.BigInteger]1) {
            $matched++
        }
    }

    if ($tested -eq 0) { return $false }
    return ($matched -eq $tested)
}

function Get-ADCSCertificateBlob {
    <#
    .SYNOPSIS
        Reads raw certificate bytes (cACertificate) from a PKI container
        object and, where present, its immediate child objects.
    .DESCRIPTION
        Used for the NTAuthCertificates object (a single object holding a
        multivalued cACertificate attribute) as well as the AIA and Root
        Certification Authorities containers (whose children each carry
        their own cACertificate). Failures are non-terminating and reported
        via Write-Verbose; a missing/inaccessible container simply yields
        no blobs.
    .OUTPUTS
        [PSCustomObject[]] with Source and Bytes properties.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$ContainerDN
    )

    $blobs = [System.Collections.ArrayList]::new()

    try {
        $obj = Get-ADObject -Identity $ContainerDN -Properties cACertificate, cn -ErrorAction Stop
        foreach ($b in @($obj.cACertificate)) {
            if ($b) { [void]$blobs.Add([PSCustomObject]@{ Source = $obj.Name; Bytes = $b }) }
        }
    }
    catch {
        Write-Verbose "Get-ADCSCertificateBlob: could not read '$ContainerDN' directly: $_"
    }

    try {
        $children = Get-ADObject -SearchBase $ContainerDN -SearchScope OneLevel -Filter * -Properties cACertificate, cn -ErrorAction Stop
        foreach ($child in $children) {
            foreach ($b in @($child.cACertificate)) {
                if ($b) { [void]$blobs.Add([PSCustomObject]@{ Source = $child.Name; Bytes = $b }) }
            }
        }
    }
    catch {
        Write-Verbose "Get-ADCSCertificateBlob: could not enumerate children of '$ContainerDN': $_"
    }

    return @($blobs)
}

function Test-ADCSWeakCertificate {
    <#
    .SYNOPSIS
        Evaluates one certificate blob for weak signature algorithm, weak
        RSA modulus size, and the ROCA fingerprint.
    .OUTPUTS
        [PSCustomObject] describing what (if anything) is weak, or $null if
        the blob could not be parsed as a certificate.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [byte[]]$Bytes,

        [Parameter(Mandatory)]
        [string]$Source
    )

    try {
        $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2(,$Bytes)
    }
    catch {
        Write-Verbose "Test-ADCSWeakCertificate: could not parse certificate from '$Source': $_"
        return $null
    }

    $sigAlgo = $cert.SignatureAlgorithm.FriendlyName
    $weakSig = $sigAlgo -match '(?i)md2|md4|md5|sha0|sha1\b'

    $isRoca = $false
    $keySize = $null
    $weakModulus = $false

    try {
        $rsa = $null
        try {
            # .NET 4.6+ extension method; not resolvable on hosts with an
            # older .NET Framework, where PowerShell reports "does not
            # contain a method named 'GetRSAPublicKey'" even though the
            # certificate itself is fine.
            $rsa = $cert.GetRSAPublicKey()
        }
        catch {
            $rsa = $null
        }
        if (-not $rsa) {
            # Fallback for older .NET Framework: the legacy (deprecated but
            # universally available since .NET 2.0) PublicKey.Key API still
            # returns an RSACryptoServiceProvider for RSA certificates.
            try {
                $legacyKey = $cert.PublicKey.Key
                if ($legacyKey -is [System.Security.Cryptography.RSACryptoServiceProvider]) {
                    $rsa = $legacyKey
                }
            }
            catch {
                Write-Verbose "Test-ADCSWeakCertificate: legacy PublicKey.Key fallback also failed for '$Source': $_"
            }
        }
        if ($rsa) {
            $keySize = $rsa.KeySize
            $weakModulus = $keySize -lt 2048
            $rsaParams = $rsa.ExportParameters($false)
            $modulusBig = ConvertTo-ADCSBigInteger -BigEndianBytes $rsaParams.Modulus
            $isRoca = Test-ADCSRocaFingerprint -Modulus $modulusBig
        }
    }
    catch {
        Write-Verbose "Test-ADCSWeakCertificate: could not evaluate RSA public key for '$Source': $_"
    }

    if (-not ($weakSig -or $weakModulus -or $isRoca)) {
        return $null
    }

    return [PSCustomObject]@{
        Source           = $Source
        Subject          = $cert.Subject
        Thumbprint       = $cert.Thumbprint
        NotAfter         = $cert.NotAfter
        SignatureAlgorithm = $sigAlgo
        KeySize          = $keySize
        WeakSignature    = $weakSig
        WeakModulus      = $weakModulus
        RocaCandidate    = $isRoca
    }
}

function Test-ADCSExtended {
    <#
    .SYNOPSIS
        Audits AD CS for ESC4, ESC8, ROCA-vulnerable keys, and weak
        signature algorithms / RSA moduli across the CA and trust store.
    .DESCRIPTION
        Extends the existing ESC1/ESC2/ESC3/ESC7 coverage in
        Test-ADCertificateServices with:
          - ESC4: certificate templates whose ACL grants Write/WriteDacl/
            WriteOwner/GenericAll/GenericWrite to a low-privileged
            principal.
          - A high-risk-without-approval check: templates that allow an
            enrollee-supplied subject/SAN or carry an Any-Purpose EKU
            without requiring manager approval (CT_FLAG_PEND_ALL_REQUESTS).
          - ESC8: CA web enrollment reachable over HTTP without Extended
            Protection for Authentication.
          - ROCA-vulnerable keys (CVE-2017-15361) and weak signature
            algorithms / RSA key sizes across the CA certificates, the
            NTAuthCertificates object, and the AIA/Root store.

        Detection only - reads template/CA attributes, ACLs, and published
        certificate bytes, plus (ESC8 only) remote service/web-configuration
        state on the CA host. Never requests, forges, or relays a
        certificate, and sends no coercion/PoC traffic.
    .PARAMETER Snapshot
        Optional snapshot hashtable (from Get-ADSnapshot). When supplied,
        certificate template/CA enumeration and the approval-gate /
        CA-certificate weak-crypto checks are read from
        Snapshot.ADCS. ESC4 (per-template ACL), ESC8 (live CA-host probe),
        and the NTAuth/AIA/Root store sweep have no snapshot representation
        and are skipped entirely in that case (offline mode performs no
        live AD/network access), consistent with Test-ADCoercionAndRelayExposure.
    .OUTPUTS
        [ADSecurityFinding[]]
    #>
    [CmdletBinding()]
    param(
        [Parameter()]
        [hashtable]$Snapshot
    )

    Write-Verbose "Starting AD CS extended security audit (ESC4/ESC8/ROCA/weak crypto)..."
    $findings = @()

    $lowPrivilegedPrincipals = @(
        'Authenticated Users'
        'Domain Users'
        'Domain Computers'
        'Everyone'
    )

    $trustedAclPrincipals = @(
        'Domain Admins'
        'Enterprise Admins'
        'Administrators'
        'SYSTEM'
        'Cert Publishers'
        'Enterprise Read-only Domain Controllers'
    )

    $certTemplates = @()
    $certAuthorities = @()
    $adcsInstalled = $false
    $configContext = $null

    if ($Snapshot) {
        if ($Snapshot.ContainsKey('ADCS') -and $Snapshot.ADCS.Installed) {
            Write-Verbose "Test-ADCSExtended: using snapshot AD CS inventory."
            $adcsInstalled = $true
            $certTemplates = @($Snapshot.ADCS.CertificateTemplates)
            $certAuthorities = @($Snapshot.ADCS.CertificateAuthorities)
        }
        else {
            Write-Verbose "Test-ADCSExtended: snapshot indicates AD CS is not installed; no findings."
            return $findings
        }
    }
    else {
        try {
            $configContext = ([ADSI]"LDAP://RootDSE").configurationNamingContext
            $pkiContainer = "CN=Public Key Services,CN=Services,$configContext"

            $certTemplates = @(Invoke-ADQueryWithRetry -OperationName 'Get certificate templates (ADCS extended audit)' -Query {
                Get-ADObject -SearchBase "CN=Certificate Templates,$pkiContainer" -Filter * -Properties * -ErrorAction Stop
            })
            $adcsInstalled = $true

            try {
                $certAuthorities = @(Invoke-ADQueryWithRetry -OperationName 'Get enrollment services (ADCS extended audit)' -Query {
                    Get-ADObject -SearchBase "CN=Enrollment Services,$pkiContainer" -Filter * -Properties * -ErrorAction Stop
                })
            }
            catch {
                Write-Verbose "Test-ADCSExtended: could not enumerate Certificate Authorities: $_"
            }
        }
        catch {
            Write-Verbose "Test-ADCSExtended: AD Certificate Services not found or accessible. Skipping AD CS extended audit."
            return $findings
        }
    }

    if (-not $certTemplates -or $certTemplates.Count -eq 0) {
        Write-Verbose "Test-ADCSExtended: no certificate templates found; skipping template-based checks."
    }

    # -------------------------------------------------------------------
    # ESC4: dangerous template ACLs (live only - not captured in snapshot)
    # -------------------------------------------------------------------
    if ($Snapshot) {
        Write-Verbose "Test-ADCSExtended: -Snapshot supplied; skipping live per-template ACL read for ESC4 (offline mode performs no live AD access)."
    }
    else {
        foreach ($template in $certTemplates) {
            $templateName = if ($template.displayName) { $template.displayName } else { $template.Name }

            $templateAcl = $null
            try {
                $templateAcl = Get-Acl -Path "AD:$($template.DistinguishedName)" -ErrorAction Stop
            }
            catch {
                Write-Verbose "Test-ADCSExtended: could not get ACL for template '$templateName': $_"
                continue
            }

            $dangerousAces = @()
            foreach ($ace in $templateAcl.Access) {
                $principal = $ace.IdentityReference.Value
                $isLowPriv = $false
                foreach ($lowPriv in $lowPrivilegedPrincipals) {
                    if ($principal -match [regex]::Escape($lowPriv)) { $isLowPriv = $true; break }
                }
                if (-not $isLowPriv) { continue }

                $isTrusted = $false
                foreach ($trusted in $trustedAclPrincipals) {
                    if ($principal -match [regex]::Escape($trusted)) { $isTrusted = $true; break }
                }
                if ($isTrusted) { continue }

                foreach ($right in $Script:DangerousStandardRights) {
                    if ($ace.ActiveDirectoryRights -match $right) {
                        $dangerousAces += "$principal ($($ace.ActiveDirectoryRights))"
                        break
                    }
                }
            }

            if ($dangerousAces.Count -gt 0) {
                $finding = [ADSecurityFinding]::new()
                $finding.Category = 'Certificate Services'
                $finding.Issue = 'Certificate Template with Weak ACL (ESC4)'
                $finding.Severity = 'High'
                $finding.SeverityLevel = 3
                $finding.AffectedObject = $templateName
                $finding.Description = "Certificate template '$templateName' grants Write/WriteDacl/WriteOwner/GenericAll/GenericWrite rights to low-privileged principal(s): $($dangerousAces -join '; ')."
                $finding.Impact = "A principal with write access to a certificate template can reconfigure it into an ESC1-style template (enable SAN, remove approval, weaken EKUs) and then enroll for a certificate impersonating any account, including Domain Admins."
                $finding.Remediation = "Remove Write/WriteDacl/WriteOwner/GenericAll/GenericWrite permissions on the template from any principal other than PKI/Domain administrators."
                $finding.Details = @{
                    DistinguishedName = $template.DistinguishedName
                    DangerousAces     = $dangerousAces -join '; '
                    ESCType           = 'ESC4'
                }
                $findings += $finding
            }
        }
    }

    # -------------------------------------------------------------------
    # High-risk-without-approval check (snapshot-aware; attribute-only)
    # Deliberately distinct from ESC1 (SAN + low-priv enrollment) and ESC2
    # (no EKU / Any-Purpose): this flags the absence of the manager
    # approval gate on templates carrying either risky property.
    # -------------------------------------------------------------------
    foreach ($template in $certTemplates) {
        $templateName = if ($template.displayName) { $template.displayName } else { $template.Name }

        $certNameFlag = $template.'msPKI-Certificate-Name-Flag'
        $enrollmentFlag = $template.'msPKI-Enrollment-Flag'
        $ekus = $template.'msPKI-Certificate-Application-Policy'
        $ekusV1 = $template.'pKIExtendedKeyUsage'

        $allowsSan = [bool]([int64]($certNameFlag) -band 1)                        # CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT
        $anyPurpose = ($ekus -contains '2.5.29.37.0') -or ($ekusV1 -contains '2.5.29.37.0')
        $requiresApproval = [bool]([int64]($enrollmentFlag) -band 2)               # CT_FLAG_PEND_ALL_REQUESTS

        if (($allowsSan -or $anyPurpose) -and -not $requiresApproval) {
            $finding = [ADSecurityFinding]::new()
            $finding.Category = 'Certificate Services'
            $finding.Issue = 'Certificate Template Allows High-Risk Enrollment Without Manager Approval'
            $finding.Severity = 'High'
            $finding.SeverityLevel = 3
            $finding.AffectedObject = $templateName
            $finding.Description = "Certificate template '$templateName' allows $(if ($allowsSan) { 'enrollee-supplied subject/SAN' }) $(if ($allowsSan -and $anyPurpose) { 'and' }) $(if ($anyPurpose) { 'an Any-Purpose EKU' }) without requiring CA manager approval (CT_FLAG_PEND_ALL_REQUESTS is not set)."
            $finding.Impact = "Certificates matching this template are issued automatically with no human review, removing a compensating control that would otherwise catch abuse of the risky template properties."
            $finding.Remediation = "Require manager approval for this template (set CT_FLAG_PEND_ALL_REQUESTS) until the SAN/Any-Purpose properties can be removed or enrollment can be restricted."
            $finding.Details = @{
                DistinguishedName = $template.DistinguishedName
                AllowsSan         = $allowsSan
                AnyPurposeEku     = $anyPurpose
                RequiresApproval  = $requiresApproval
            }
            $findings += $finding
        }
    }

    # -------------------------------------------------------------------
    # ESC8: CA web enrollment over HTTP without EPA (live only)
    # -------------------------------------------------------------------
    if ($Snapshot) {
        Write-Verbose "Test-ADCSExtended: -Snapshot supplied; skipping live ESC8 web-enrollment probe (offline mode performs no live AD/network access)."
    }
    else {
        foreach ($ca in $certAuthorities) {
            $caName = $ca.Name
            $caHost = $ca.dNSHostName
            if (-not $caHost) {
                Write-Verbose "Test-ADCSExtended: CA '$caName' has no dNSHostName; skipping ESC8 probe."
                continue
            }

            try {
                $webEnrollState = Invoke-ADQueryWithRetry -OperationName "Probe CA web enrollment on $caHost" -Query {
                    Invoke-Command -ComputerName $caHost -ErrorAction Stop -ScriptBlock {
                        $result = [PSCustomObject]@{
                            CertSrvVDirPresent = $false
                            EpaRequired        = $null
                            Error              = $null
                        }
                        try {
                            Import-Module WebAdministration -ErrorAction Stop
                            $vdir = Get-WebApplication -Site 'Default Web Site' -Name 'CertSrv' -ErrorAction SilentlyContinue
                            if ($vdir) {
                                $result.CertSrvVDirPresent = $true
                                try {
                                    $epa = Get-WebConfigurationProperty -PSPath 'IIS:\Sites\Default Web Site\CertSrv' `
                                        -Filter 'system.webServer/security/authentication/windowsAuthentication' `
                                        -Name 'extendedProtection.tokenChecking' -ErrorAction Stop
                                    $result.EpaRequired = ($epa.Value -eq 'Require')
                                }
                                catch {
                                    $result.EpaRequired = $null
                                }
                            }
                        }
                        catch {
                            $result.Error = "$_"
                        }
                        return $result
                    }
                }
            }
            catch {
                Write-Verbose "Test-ADCSExtended: could not probe CA host '$caHost' for web enrollment state: $_"
                $webEnrollState = $null
            }

            if ($webEnrollState -and $webEnrollState.CertSrvVDirPresent) {
                $epaMissing = ($webEnrollState.EpaRequired -ne $true)
                if ($epaMissing) {
                    $finding = [ADSecurityFinding]::new()
                    $finding.Category = 'Certificate Services'
                    $finding.Issue = 'CA Web Enrollment over HTTP (ESC8)'
                    $finding.Severity = 'Critical'
                    $finding.SeverityLevel = 4
                    $finding.AffectedObject = $caName
                    $finding.Description = "Certificate Authority '$caName' ($caHost) has the CertSrv web enrollment endpoint installed without Extended Protection for Authentication (EPA) enforced."
                    $finding.Impact = "An attacker who coerces a privileged host (e.g. a Domain Controller) to authenticate to them can relay that NTLM authentication to the CA's HTTP enrollment endpoint and obtain a certificate as that host/account, leading to domain compromise."
                    $finding.Remediation = "Disable HTTP(S) web enrollment if unused, or require Extended Protection for Authentication ('Require') on the CertSrv virtual directory and enforce HTTPS with channel binding."
                    $finding.Details = @{
                        DistinguishedName = $ca.DistinguishedName
                        CAHost            = $caHost
                        EpaRequired       = $webEnrollState.EpaRequired
                        ESCType           = 'ESC8'
                    }
                    $findings += $finding
                }
            }
            elseif ($webEnrollState -and $webEnrollState.Error) {
                Write-Verbose "Test-ADCSExtended: web enrollment probe on '$caHost' reported: $($webEnrollState.Error)"
            }
        }
    }

    # -------------------------------------------------------------------
    # ROCA / weak signature sweep of the CA's own certificate(s)
    # (snapshot-aware: uses cACertificate already captured on CA objects).
    # -------------------------------------------------------------------
    $weakCertResults = [System.Collections.ArrayList]::new()

    foreach ($ca in $certAuthorities) {
        foreach ($b in @($ca.'cACertificate')) {
            if (-not $b) { continue }
            $result = Test-ADCSWeakCertificate -Bytes $b -Source "CA:$($ca.Name)"
            if ($result) { [void]$weakCertResults.Add($result) }
        }
    }

    # -------------------------------------------------------------------
    # NTAuth / AIA / Root store sweep (live only - not captured in snapshot)
    # -------------------------------------------------------------------
    if ($Snapshot) {
        Write-Verbose "Test-ADCSExtended: -Snapshot supplied; skipping live NTAuth/AIA/Root store read (offline mode performs no live AD access)."
    }
    else {
        try {
            $pkiContainer = "CN=Public Key Services,CN=Services,$configContext"
            $storeTargets = @{
                'NTAuth' = "CN=NTAuthCertificates,$pkiContainer"
                'AIA'    = "CN=AIA,$pkiContainer"
                'Root'   = "CN=Certification Authorities,$pkiContainer"
            }

            foreach ($storeName in $storeTargets.Keys) {
                $blobs = Get-ADCSCertificateBlob -ContainerDN $storeTargets[$storeName]
                foreach ($blob in $blobs) {
                    $result = Test-ADCSWeakCertificate -Bytes $blob.Bytes -Source "$storeName`:$($blob.Source)"
                    if ($result) { [void]$weakCertResults.Add($result) }
                }
            }
        }
        catch {
            Write-Verbose "Test-ADCSExtended: could not sweep NTAuth/AIA/Root store: $_"
        }
    }

    foreach ($weak in $weakCertResults) {
        if ($weak.RocaCandidate) {
            $finding = [ADSecurityFinding]::new()
            $finding.Category = 'Certificate Services'
            $finding.Issue = 'ROCA-Vulnerable Certificate Key'
            $finding.Severity = 'High'
            $finding.SeverityLevel = 3
            $finding.AffectedObject = $weak.Source
            $finding.Description = "Certificate '$($weak.Subject)' (thumbprint $($weak.Thumbprint)) from $($weak.Source) matches the ROCA (CVE-2017-15361) weak-key fingerprint for RSA keys generated by the affected Infineon RSALib."
            $finding.Impact = "ROCA-vulnerable RSA keys can, with sufficient compute, have their private key factored from the public key alone, fully compromising anything the certificate protects or authenticates."
            $finding.Remediation = "Confirm with a dedicated ROCA-detection tool, then revoke and reissue the certificate with a key generated by an unaffected library."
            $finding.Details = @{
                Source             = $weak.Source
                Subject            = $weak.Subject
                Thumbprint         = $weak.Thumbprint
                KeySize            = $weak.KeySize
                SignatureAlgorithm = $weak.SignatureAlgorithm
                Note               = 'Probabilistic fingerprint test; confirm before remediation.'
            }
            $findings += $finding
        }

        if ($weak.WeakSignature -or $weak.WeakModulus) {
            $reasons = @()
            if ($weak.WeakSignature) { $reasons += "weak signature algorithm ($($weak.SignatureAlgorithm))" }
            if ($weak.WeakModulus) { $reasons += "RSA key size below 2048 bits ($($weak.KeySize) bits)" }

            $finding = [ADSecurityFinding]::new()
            $finding.Category = 'Certificate Services'
            $finding.Issue = 'Weak Signature Algorithm in PKI Trust Store'
            $finding.Severity = 'Medium'
            $finding.SeverityLevel = 2
            $finding.AffectedObject = $weak.Source
            $finding.Description = "Certificate '$($weak.Subject)' (thumbprint $($weak.Thumbprint)) from $($weak.Source) has $($reasons -join ' and ')."
            $finding.Impact = "Weak signature algorithms (MD2/MD4/MD5/SHA0/SHA1) or undersized RSA keys undermine the integrity of the certificate chain and any trust decisions made against it."
            $finding.Remediation = "Reissue the certificate with SHA-256 (or better) and an RSA key of at least 2048 bits (3072+ recommended for CA certificates)."
            $finding.Details = @{
                Source             = $weak.Source
                Subject            = $weak.Subject
                Thumbprint         = $weak.Thumbprint
                KeySize            = $weak.KeySize
                SignatureAlgorithm = $weak.SignatureAlgorithm
                NotAfter           = $weak.NotAfter
            }
            $findings += $finding
        }
    }

    Write-Verbose "AD CS extended audit complete. Found $($findings.Count) issues."
    return $findings
}

#endregion
