#region Certificate Services Extended Audits (ESC4, ESC8, ROCA, weak PKI crypto)
#
# Extends src/CertificateServicesAudits.ps1 (ESC1/ESC2/ESC3/ESC7) with the
# remaining PingCastle-comparable AD CS checks:
#
#   - ESC4  : dangerous ACLs on certificate templates (Write/WriteDacl/
#             WriteOwner/GenericAll/GenericWrite granted to low-privileged
#             principals), which let an attacker rewrite a template into an
#             ESC1-style template.
#   - ESC8  : CA web enrollment reachable over HTTP without Extended
#             Protection for Authentication (EPA), enabling NTLM relay to
#             the enrollment endpoint.
#   - A high-risk-without-approval check that flags templates combining
#     enrollee-supplied subject/SAN or an Any-Purpose EKU with no manager
#     approval gate (CT_FLAG_PEND_ALL_REQUESTS unset). This is deliberately
#     scoped differently from the existing ESC1 (SAN + low-priv enrollment)
#     and ESC2 (no EKU / Any-Purpose) checks so it does not duplicate them.
#   - ROCA-vulnerable keys (CVE-2017-15361) and weak signature algorithms /
#     RSA moduli across the CA certificates, NTAuth store, and AIA/Root
#     store published in the Configuration partition.
#
# PingCastle-comparable check(s): A-CertEnrollHttp, A-CertTempNoSecurity,
# A-CertTempAnyPurpose, A-CertTempAnyone, A-CertTempCustomSubject,
# A-CertROCA, A-CertWeakRsaComponent, A-MD5RootCert, A-SHA1RootCert.
#
# DETECTION ONLY: every check here reads AD attributes/ACLs, certificate
# bytes already published in AD, or (for ESC8 only) remote service/registry
# state on the CA host itself. Nothing here requests, forges, or relays a
# certificate, and no coercion/PoC traffic is sent to any host.
#
# Detection scope: certificate template/CA enumeration, ESC4 (per-template
# ACL), the approval-gate/CA-certificate weak-crypto checks, and the
# NTAuth/AIA/Root store sweep are all live AD reads. ESC8 is a live network
# probe of the CA host itself. Nothing here is snapshot-based.

# Small set of primes (with a fast brute-force order computation, valid
# since each prime here is tiny) used for a probabilistic ROCA fingerprint
# test. A modulus is treated as a ROCA candidate only when the discrete-log
# style test below holds for every one of these primes; this mirrors the
# public description of the ROCA (CVE-2017-15361) fingerprinting technique
# but is a heuristic re-implementation, not a copy of any vendor/tool code.
$Script:ADCSRocaTestPrimes = @(3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,101,103,107,109,113)

function ConvertTo-ADCSBigInteger {
    <#
    .SYNOPSIS
        Converts a big-endian unsigned byte array (as returned by
        RSAParameters.Modulus) into a positive [System.Numerics.BigInteger].
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [byte[]]$BigEndianBytes
    )

    $little = [byte[]]$BigEndianBytes.Clone()
    [Array]::Reverse($little)
    # Append a trailing zero byte so BigInteger (which is little-endian,
    # two's-complement) never interprets the value as negative.
    $withSign = New-Object byte[] ($little.Length + 1)
    [Array]::Copy($little, $withSign, $little.Length)
    return [System.Numerics.BigInteger]::new($withSign)
}

function Test-ADCSRocaFingerprint {
    <#
    .SYNOPSIS
        Heuristic ROCA (CVE-2017-15361) fingerprint test for an RSA modulus.
    .DESCRIPTION
        For each small prime p in $Script:ADCSRocaTestPrimes, computes the
        multiplicative order of 65537 mod p, then checks whether
        (N mod p) raised to that order is congruent to 1 mod p - the
        signature of a modulus generated by the affected Infineon RSALib
        key-generation routine. Flags the modulus only when the test holds
        for every prime evaluated. This is a probabilistic filter (as the
        public description of ROCA detection is), not a certainty; genuine
        candidates should be confirmed with a dedicated ROCA-detection tool
        before remediation is prioritised.
    .OUTPUTS
        [bool]
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [System.Numerics.BigInteger]$Modulus
    )

    $tested = 0
    $matched = 0

    foreach ($p in $Script:ADCSRocaTestPrimes) {
        $pBig = [System.Numerics.BigInteger]$p
        $g = [System.Numerics.BigInteger]65537 % $pBig
        if ($g -eq [System.Numerics.BigInteger]0) { continue }

        # Brute-force multiplicative order of g mod p (p is tiny, so this
        # is at most p-1 iterations).
        $order = 1
        $val = $g
        while ($val -ne [System.Numerics.BigInteger]1 -and $order -le $p) {
            $val = ($val * $g) % $pBig
            $order++
        }

        $nModP = $Modulus % $pBig
        if ($nModP -eq [System.Numerics.BigInteger]0) { continue }

        $tested++
        $result = [System.Numerics.BigInteger]::ModPow($nModP, $order, $pBig)
        if ($result -eq [System.Numerics.BigInteger]1) {
            $matched++
        }
    }

    if ($tested -eq 0) { return $false }
    return ($matched -eq $tested)
}

function Get-ADCSCertificateBlob {
    <#
    .SYNOPSIS
        Reads raw certificate bytes (cACertificate) from a PKI container
        object and, where present, its immediate child objects.
    .DESCRIPTION
        Used for the NTAuthCertificates object (a single object holding a
        multivalued cACertificate attribute) as well as the AIA and Root
        Certification Authorities containers (whose children each carry
        their own cACertificate). Failures are non-terminating and reported
        via Write-Verbose; a missing/inaccessible container simply yields
        no blobs.
    .OUTPUTS
        [PSCustomObject[]] with Source and Bytes properties.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$ContainerDN,

        [Parameter()]
        [string]$Server
    )

    $blobs = [System.Collections.ArrayList]::new()

    try {
        $obj = Get-ADObject -Identity $ContainerDN -Properties cACertificate, cn -Server $Server -ErrorAction Stop
        foreach ($b in @($obj.cACertificate)) {
            if ($b) { [void]$blobs.Add([PSCustomObject]@{ Source = $obj.Name; Bytes = $b }) }
        }
    }
    catch {
        Write-Verbose "Get-ADCSCertificateBlob: could not read '$ContainerDN' directly: $_"
    }

    try {
        $children = Get-ADObject -SearchBase $ContainerDN -SearchScope OneLevel -Filter * -Properties cACertificate, cn -Server $Server -ErrorAction Stop
        foreach ($child in $children) {
            foreach ($b in @($child.cACertificate)) {
                if ($b) { [void]$blobs.Add([PSCustomObject]@{ Source = $child.Name; Bytes = $b }) }
            }
        }
    }
    catch {
        Write-Verbose "Get-ADCSCertificateBlob: could not enumerate children of '$ContainerDN': $_"
    }

    return @($blobs)
}

function Test-ADCSWeakCertificate {
    <#
    .SYNOPSIS
        Evaluates one certificate blob for weak signature algorithm, weak
        RSA modulus size, and the ROCA fingerprint.
    .OUTPUTS
        [PSCustomObject] describing what (if anything) is weak, or $null if
        the blob could not be parsed as a certificate.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [byte[]]$Bytes,

        [Parameter(Mandatory)]
        [string]$Source
    )

    try {
        $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2(,$Bytes)
    }
    catch {
        Write-Verbose "Test-ADCSWeakCertificate: could not parse certificate from '$Source': $_"
        return $null
    }

    $sigAlgo = $cert.SignatureAlgorithm.FriendlyName
    $weakSig = $sigAlgo -match '(?i)md2|md4|md5|sha0|sha1\b'

    $isRoca = $false
    $keySize = $null
    $weakModulus = $false

    try {
        $rsa = $null
        try {
            # .NET 4.6+ extension method; not resolvable on hosts with an
            # older .NET Framework, where PowerShell reports "does not
            # contain a method named 'GetRSAPublicKey'" even though the
            # certificate itself is fine.
            $rsa = $cert.GetRSAPublicKey()
        }
        catch {
            $rsa = $null
        }
        if (-not $rsa) {
            # Fallback for older .NET Framework: the legacy (deprecated but
            # universally available since .NET 2.0) PublicKey.Key API still
            # returns an RSACryptoServiceProvider for RSA certificates.
            try {
                $legacyKey = $cert.PublicKey.Key
                if ($legacyKey -is [System.Security.Cryptography.RSACryptoServiceProvider]) {
                    $rsa = $legacyKey
                }
            }
            catch {
                Write-Verbose "Test-ADCSWeakCertificate: legacy PublicKey.Key fallback also failed for '$Source': $_"
            }
        }
        if ($rsa) {
            $keySize = $rsa.KeySize
            $weakModulus = $keySize -lt 2048
            $rsaParams = $rsa.ExportParameters($false)
            $modulusBig = ConvertTo-ADCSBigInteger -BigEndianBytes $rsaParams.Modulus
            $isRoca = Test-ADCSRocaFingerprint -Modulus $modulusBig
        }
    }
    catch {
        Write-Verbose "Test-ADCSWeakCertificate: could not evaluate RSA public key for '$Source': $_"
    }

    if (-not ($weakSig -or $weakModulus -or $isRoca)) {
        return $null
    }

    return [PSCustomObject]@{
        Source           = $Source
        Subject          = $cert.Subject
        Thumbprint       = $cert.Thumbprint
        NotAfter         = $cert.NotAfter
        SignatureAlgorithm = $sigAlgo
        KeySize          = $keySize
        WeakSignature    = $weakSig
        WeakModulus      = $weakModulus
        RocaCandidate    = $isRoca
    }
}

function Test-ADCSExtended {
    <#
    .SYNOPSIS
        Audits AD CS for ESC4, ESC8, ROCA-vulnerable keys, and weak
        signature algorithms / RSA moduli across the CA and trust store.
    .DESCRIPTION
        Extends the existing ESC1/ESC2/ESC3/ESC7 coverage in
        Test-ADCertificateServices with:
          - ESC4: certificate templates whose ACL grants Write/WriteDacl/
            WriteOwner/GenericAll/GenericWrite to a low-privileged
            principal.
          - A high-risk-without-approval check: templates that allow an
            enrollee-supplied subject/SAN or carry an Any-Purpose EKU
            without requiring manager approval (CT_FLAG_PEND_ALL_REQUESTS).
          - ESC8: CA web enrollment reachable over HTTP without Extended
            Protection for Authentication.
          - ROCA-vulnerable keys (CVE-2017-15361) and weak signature
            algorithms / RSA key sizes across the CA certificates, the
            NTAuthCertificates object, and the AIA/Root store.
          - ESC15 ("EKUwu", CVE-2024-49019): a Schema Version 1 template
            with low-privileged enrollment and no manager-approval gate,
            which lets a requester inject arbitrary Application Policy
            OIDs into the CSR, bypassing the template's declared EKUs.

        Detection only - reads template/CA attributes, ACLs, and published
        certificate bytes, plus (ESC8 only) remote service/web-configuration
        state on the CA host. Never requests, forges, or relays a
        certificate, and sends no coercion/PoC traffic.
    .OUTPUTS
        [ADSecurityFinding[]]
    #>
    [CmdletBinding()]
    param()

    Write-Verbose "Starting AD CS extended security audit (ESC4/ESC8/ROCA/weak crypto)..."
    $findings = @()

    $lowPrivilegedPrincipals = @(
        'Authenticated Users'
        'Domain Users'
        'Domain Computers'
        'Everyone'
    )

    $trustedAclPrincipals = @(
        'Domain Admins'
        'Enterprise Admins'
        'Administrators'
        'SYSTEM'
        'Cert Publishers'
        'Enterprise Read-only Domain Controllers'
    )

    $certTemplates = @()
    $certAuthorities = @()
    $adcsInstalled = $false
    $configContext = $null

    try {
        $__adServer = Get-ADSecurityAuditTargetServerValue
        $configContext = Get-ADRootDSEValue -Property configurationNamingContext -Server $__adServer
        $pkiContainer = "CN=Public Key Services,CN=Services,$configContext"

        # -SearchScope OneLevel, not the default Subtree: a Subtree
        # search over "CN=Certificate Templates,..."/"CN=Enrollment
        # Services,..." returns the CONTAINER OBJECT ITSELF alongside
        # its real children (pKICertificateTemplate/pKIEnrollmentService
        # objects, which are never nested further than one level under
        # these containers). Neither loop below filtered by objectClass,
        # so that container object was silently iterated as if it were
        # a real template/CA - its own Name IS literally "Certificate
        # Templates"/"Enrollment Services", it has no dNSHostName or
        # cACertificate, and every check against it either produced
        # confusing noise (e.g. "CA 'Enrollment Services' has no
        # dNSHostName; skipping ESC8 probe" - about the container, not
        # any real, misconfigured CA) or was silently skipped. OneLevel
        # returns only the real child objects, never the base container.
        $certTemplates = @(Invoke-ADQueryWithRetry -OperationName 'Get certificate templates (ADCS extended audit)' -Query {
            Get-ADObject -SearchBase "CN=Certificate Templates,$pkiContainer" -SearchScope OneLevel -Filter * -Properties * -Server $__adServer -ErrorAction Stop
        })
        $adcsInstalled = $true

        try {
            $certAuthorities = @(Invoke-ADQueryWithRetry -OperationName 'Get enrollment services (ADCS extended audit)' -Query {
                Get-ADObject -SearchBase "CN=Enrollment Services,$pkiContainer" -SearchScope OneLevel -Filter * -Properties * -Server $__adServer -ErrorAction Stop
            })
        }
        catch {
            Write-Verbose "Test-ADCSExtended: could not enumerate Certificate Authorities: $_"
        }
    }
    catch {
        Write-Verbose "Test-ADCSExtended: AD Certificate Services not found or accessible. Skipping AD CS extended audit."
        return $findings
    }

    if (-not $certTemplates -or $certTemplates.Count -eq 0) {
        Write-Verbose "Test-ADCSExtended: no certificate templates found; skipping template-based checks."
    }

    # -------------------------------------------------------------------
    # ESC4: dangerous template ACLs
    # -------------------------------------------------------------------
    foreach ($template in $certTemplates) {
        $templateName = if ($template.displayName) { $template.displayName } else { $template.Name }

        $templateAces = try {
            # Get-ADObject -Properties nTSecurityDescriptor, not
            # Get-Acl -Path "AD:..." - the latter has no -Server
            # parameter and reads via the AD: PSDrive's ambient
            # default domain/DC, bypassing this module's -Server
            # override entirely. nTSecurityDescriptor returns the
            # same ActiveDirectorySecurity object (.Access, etc.) via
            # a real, -Server-aware Get-AD* cmdlet.
            @((Get-ADObject -Identity $template.DistinguishedName -Properties nTSecurityDescriptor -Server $__adServer -ErrorAction Stop).nTSecurityDescriptor.Access)
        }
        catch {
            Write-Verbose "Test-ADCSExtended: could not get ACL for template '$templateName': $_"
            @()
        }

        $dangerousAces = @()
        foreach ($ace in $templateAces) {
            $principal = $ace.IdentityReference.Value
            $isLowPriv = $false
            foreach ($lowPriv in $lowPrivilegedPrincipals) {
                if ($principal -match [regex]::Escape($lowPriv)) { $isLowPriv = $true; break }
            }
            if (-not $isLowPriv) { continue }

            $isTrusted = $false
            foreach ($trusted in $trustedAclPrincipals) {
                if ($principal -match [regex]::Escape($trusted)) { $isTrusted = $true; break }
            }
            if ($isTrusted) { continue }

            foreach ($right in $Script:DangerousStandardRights) {
                if ($ace.ActiveDirectoryRights -match $right) {
                    $dangerousAces += "$principal ($($ace.ActiveDirectoryRights))"
                    break
                }
            }
        }
        # A template can grant the same low-priv principal the same
        # dangerous right via more than one ACE (one per property
        # set/object type) - dedupe so the same "principal (rights)" line
        # doesn't appear twice in one finding's bullet list.
        $dangerousAces = @($dangerousAces | Select-Object -Unique)

        if ($dangerousAces.Count -gt 0) {
            $finding = [ADSecurityFinding]::new()
            $finding.Category = 'Certificate Services'
            $finding.Issue = 'Certificate Template with Weak ACL (ESC4)'
            $finding.Severity = 'High'
            $finding.SeverityLevel = 3
            $finding.AffectedObject = $templateName
            # BUGFIX: was a single semicolon-joined run-on sentence; rendered
            # as one bullet per ACE instead for readability once there's more
            # than a couple of principals.
            $dangerousAceBullets = ($dangerousAces | ForEach-Object { "- $_" }) -join "`n"
            $finding.Description = "Certificate template '$templateName' grants Write/WriteDacl/WriteOwner/GenericAll/GenericWrite rights to low-privileged principal(s):`n$dangerousAceBullets"
            $finding.Impact = "A principal with write access to a certificate template can reconfigure it into an ESC1-style template (enable SAN, remove approval, weaken EKUs) and then enroll for a certificate impersonating any account, including Domain Admins."
            $finding.Remediation = "Remove Write/WriteDacl/WriteOwner/GenericAll/GenericWrite permissions on the template from any principal other than PKI/Domain administrators."
            $finding.EstimatedEffort = 'Medium - a single-template ACE removal, but confirm the trustee isn''t a legitimate certificate-lifecycle-management tool or service account before removing.'
            $finding.KnownRisks = 'Procedural - confirm the trustee isn''t an active cert-management automation account before removing; no realistic legitimate technical break otherwise.'
            $finding.BackupRollback = 'Moderate - export the template''s ACL (certutil -v -template or PSPKI) before changing it so the exact ACE can be restored if needed.'
            $finding.Details = @{
                DistinguishedName = $template.DistinguishedName
                DangerousAces     = $dangerousAces -join '; '
                ESCType           = 'ESC4'
            }
            $findings += $finding
        }
    }

    # -------------------------------------------------------------------
    # ESC5: dangerous ACLs on non-template PKI container objects
    # -------------------------------------------------------------------
    # Same shape as ESC4 above (Write/WriteDacl/WriteOwner/GenericAll/
    # GenericWrite held by a low-privileged principal), applied to the PKI
    # container objects themselves rather than individual templates. A
    # write on "Enrollment Services" lets an attacker publish a rogue CA
    # or reconfigure an existing pKIEnrollmentService object's flags
    # (chaining into ESC6/ESC11-style abuse without ever touching the CA
    # server itself); a write on "OID" lets an attacker create/modify an
    # Issuance Policy OID object (a precondition for ESC13, below); a
    # write on the "Public Key Services" container itself is broader
    # still. NTAuthCertificates and AIA are checked for weak signature/
    # ROCA content by Test-ADCSWeakCertificate already, so this adds ACL
    # coverage rather than duplicating that.
    $pkiAclTargets = @(
        [PSCustomObject]@{ Name = 'Public Key Services'; DN = $pkiContainer }
        [PSCustomObject]@{ Name = 'AIA'; DN = "CN=AIA,$pkiContainer" }
        [PSCustomObject]@{ Name = 'Certification Authorities'; DN = "CN=Certification Authorities,$pkiContainer" }
        [PSCustomObject]@{ Name = 'Enrollment Services'; DN = "CN=Enrollment Services,$pkiContainer" }
        [PSCustomObject]@{ Name = 'KRA'; DN = "CN=KRA,$pkiContainer" }
        [PSCustomObject]@{ Name = 'OID'; DN = "CN=OID,$pkiContainer" }
    )

    foreach ($pkiTarget in $pkiAclTargets) {
        $pkiAces = try {
            @((Get-ADObject -Identity $pkiTarget.DN -Properties nTSecurityDescriptor -Server $__adServer -ErrorAction Stop).nTSecurityDescriptor.Access)
        }
        catch {
            # A missing object here (e.g. no KRA ever configured) is
            # normal, not an error worth surfacing - only unexpected
            # failures are worth a Verbose note.
            Write-Verbose "Test-ADCSExtended: could not get ACL for PKI container '$($pkiTarget.Name)' ('$($pkiTarget.DN)'): $_"
            @()
        }

        $dangerousPkiAces = @()
        foreach ($ace in $pkiAces) {
            $principal = $ace.IdentityReference.Value
            $isLowPriv = $false
            foreach ($lowPriv in $lowPrivilegedPrincipals) {
                if ($principal -match [regex]::Escape($lowPriv)) { $isLowPriv = $true; break }
            }
            if (-not $isLowPriv) { continue }

            $isTrusted = $false
            foreach ($trusted in $trustedAclPrincipals) {
                if ($principal -match [regex]::Escape($trusted)) { $isTrusted = $true; break }
            }
            if ($isTrusted) { continue }

            foreach ($right in $Script:DangerousStandardRights) {
                if ($ace.ActiveDirectoryRights -match $right) {
                    $dangerousPkiAces += "$principal ($($ace.ActiveDirectoryRights))"
                    break
                }
            }
        }
        $dangerousPkiAces = @($dangerousPkiAces | Select-Object -Unique)

        if ($dangerousPkiAces.Count -gt 0) {
            $finding = [ADSecurityFinding]::new()
            $finding.Category = 'Certificate Services'
            $finding.Issue = 'Weak ACL on PKI Container Object (ESC5)'
            $finding.Severity = 'Critical'
            $finding.SeverityLevel = 4
            $finding.AffectedObject = $pkiTarget.Name
            $dangerousPkiAceBullets = ($dangerousPkiAces | ForEach-Object { "- $_" }) -join "`n"
            $finding.Description = "The '$($pkiTarget.Name)' PKI container grants Write/WriteDacl/WriteOwner/GenericAll/GenericWrite rights to low-privileged principal(s):`n$dangerousPkiAceBullets"
            $finding.Impact = "A principal with write access to this container can reconfigure PKI infrastructure at a level broader than any single template - publishing a rogue CA (via Enrollment Services), creating a malicious Issuance Policy OID (via OID), or otherwise altering how the entire PKI trusts and issues certificates, without needing access to the CA server itself."
            $finding.Remediation = "Remove Write/WriteDacl/WriteOwner/GenericAll/GenericWrite permissions on this container from any principal other than PKI/Domain administrators."
            $finding.EstimatedEffort = 'Medium - a container-level ACE removal; confirm the trustee isn''t a legitimate PKI-management tool or delegated administrator before removing.'
            $finding.KnownRisks = 'Procedural - confirm the trustee isn''t an active PKI-management automation account or delegated admin before removing; no realistic legitimate technical break otherwise.'
            $finding.BackupRollback = 'Moderate - export the container''s ACL (dsacls or PSPKI) before changing it so the exact ACE can be restored if needed.'
            $finding.Details = @{
                DistinguishedName = $pkiTarget.DN
                DangerousAces     = $dangerousPkiAces -join '; '
                ESCType           = 'ESC5'
            }
            $findings += $finding
        }
    }

    # -------------------------------------------------------------------
    # ESC9: template configured with CT_FLAG_NO_SECURITY_EXTENSION
    # -------------------------------------------------------------------
    # CT_FLAG_NO_SECURITY_EXTENSION = 0x00080000 on msPKI-Enrollment-Flag:
    # the CA omits the szOID_NTDS_CA_SECURITY_EXT (SID-binding) extension
    # from every certificate this template issues. On its own this is a
    # weakening, not an immediate compromise - the real exploit path needs
    # a second condition (a weak/compatibility certificate-mapping mode on
    # the Domain Controllers, checked separately below as ESC10) plus a
    # low-privileged enrollee who can also write to a victim account's
    # mapping attribute (e.g. userPrincipalName). Flagged whenever the
    # template both has this flag AND allows low-privileged enrollment,
    # since that's the half of the precondition this template alone
    # controls - severity stays High rather than Critical because full
    # exploitability also depends on ESC10's DC-side state.
    foreach ($template in $certTemplates) {
        $templateName = if ($template.displayName) { $template.displayName } else { $template.Name }
        $enrollmentFlag9 = $template.'msPKI-Enrollment-Flag'

        if (-not ($enrollmentFlag9 -band 0x80000)) { continue }

        $templateAcl9 = try {
            (Get-ADObject -Identity $template.DistinguishedName -Properties nTSecurityDescriptor -Server $__adServer -ErrorAction Stop).nTSecurityDescriptor
        }
        catch {
            Write-Verbose "Test-ADCSExtended: could not get ACL for template '$templateName' (ESC9 check): $_"
            $null
        }

        $hasLowPrivEnrollment9 = $false
        $enrollmentPrincipals9 = @()
        if ($templateAcl9) {
            foreach ($ace in $templateAcl9.Access) {
                if ($ace.ActiveDirectoryRights -match 'ExtendedRight|GenericAll') {
                    $principalName = $ace.IdentityReference.Value
                    foreach ($lowPriv in $lowPrivilegedPrincipals) {
                        if ($principalName -match [regex]::Escape($lowPriv)) {
                            $hasLowPrivEnrollment9 = $true
                            $enrollmentPrincipals9 += $principalName
                        }
                    }
                }
            }
        }
        $enrollmentPrincipals9 = @($enrollmentPrincipals9 | Select-Object -Unique)

        if ($hasLowPrivEnrollment9) {
            $finding = [ADSecurityFinding]::new()
            $finding.Category = 'Certificate Services'
            $finding.Issue = 'Certificate Template Missing Security Extension (ESC9)'
            $finding.Severity = 'High'
            $finding.SeverityLevel = 3
            $finding.AffectedObject = $templateName
            $finding.Description = "Certificate template '$templateName' has CT_FLAG_NO_SECURITY_EXTENSION set (omits the SID-binding extension from issued certificates) and allows enrollment by low-privileged principal(s): $($enrollmentPrincipals9 -join ', ')."
            $finding.Impact = "Certificates from this template carry no SID binding to the enrollee's AD object. If a Domain Controller is also not enforcing strong certificate mapping (see the separate ESC10/'Weak Certificate Binding Compensation' finding), a low-privileged enrollee who can also modify a victim account's userPrincipalName (or equivalent mapping attribute) can enroll for a certificate that authenticates as that victim - including a privileged account."
            $finding.Remediation = "Clear CT_FLAG_NO_SECURITY_EXTENSION on this template unless there's a specific, understood reason it's needed. If it must remain set, ensure every Domain Controller enforces strong certificate mapping (StrongCertificateBindingEnforcement) with no CertificateBackdatingCompensation opt-out active, and restrict this template's enrollment rights."
            $finding.EstimatedEffort = 'Low - a single template flag; confirm no legitimate enrollment workflow depends on the omitted extension first (rare).'
            $finding.KnownRisks = 'Minimal - clearing this flag only adds information to newly-issued certificates; it does not change any existing legitimate authentication behavior.'
            $finding.BackupRollback = 'Easy - AD CS templates are versioned, so the prior flag value can be restored and republished if needed.'
            $finding.Details = @{
                DistinguishedName    = $template.DistinguishedName
                EnrollmentFlag       = $enrollmentFlag9
                EnrollmentPrincipals = $enrollmentPrincipals9 -join '; '
                ESCType              = 'ESC9'
            }
            $findings += $finding
        }
    }

    # -------------------------------------------------------------------
    # ESC13: template's Issuance Policy OID linked to a privileged group
    # -------------------------------------------------------------------
    # msDS-OIDToGroupLink on an Issuance Policy OID object automatically
    # grants membership in the linked group to anyone authenticating with
    # a certificate carrying that policy OID - a feature meant for AD FS
    # claims-based scenarios, but exploitable when combined with a
    # template that both references the OID and allows low-privileged
    # enrollment with a client-authentication-capable EKU. One AD query
    # to build the OID -> group-link lookup, reused across every template.
    $oidToGroupLink = @{}
    try {
        $oidObjects = @(Invoke-ADQueryWithRetry -OperationName 'Get Issuance Policy OID objects (ESC13 check)' -Query {
            Get-ADObject -SearchBase "CN=OID,$pkiContainer" -SearchScope OneLevel -Filter "objectClass -eq 'msPKI-Enterprise-Oid'" -Properties msPKI-Cert-Template-OID, msDS-OIDToGroupLink -Server $__adServer -ErrorAction Stop
        })
        foreach ($oidObj in $oidObjects) {
            if ($oidObj.'msDS-OIDToGroupLink' -and $oidObj.'msPKI-Cert-Template-OID') {
                $oidToGroupLink[$oidObj.'msPKI-Cert-Template-OID'] = $oidObj.'msDS-OIDToGroupLink'
            }
        }
    }
    catch {
        Write-Verbose "Test-ADCSExtended: could not enumerate Issuance Policy OID objects for ESC13 check: $_"
    }

    $clientAuthEkus = @('1.3.6.1.5.5.7.3.2', '1.3.6.1.4.1.311.20.2.2', '1.3.6.1.5.2.3.4', '2.5.29.37.0')

    if ($oidToGroupLink.Count -gt 0) {
        foreach ($template in $certTemplates) {
            $templateName13 = if ($template.displayName) { $template.displayName } else { $template.Name }
            $issuancePolicies = @($template.'msPKI-Certificate-Policy')
            if ($issuancePolicies.Count -eq 0) { continue }

            $linkedGroups = @()
            foreach ($policyOid in $issuancePolicies) {
                if ($oidToGroupLink.ContainsKey($policyOid)) {
                    $linkedGroups += $oidToGroupLink[$policyOid]
                }
            }
            if ($linkedGroups.Count -eq 0) { continue }

            $ekus13 = @($template.'msPKI-Certificate-Application-Policy') + @($template.'pKIExtendedKeyUsage')
            $hasClientAuthEku = [bool]($clientAuthEkus | Where-Object { $ekus13 -contains $_ })
            if (-not $hasClientAuthEku) { continue }

            $templateAcl13 = try {
                (Get-ADObject -Identity $template.DistinguishedName -Properties nTSecurityDescriptor -Server $__adServer -ErrorAction Stop).nTSecurityDescriptor
            }
            catch {
                Write-Verbose "Test-ADCSExtended: could not get ACL for template '$templateName13' (ESC13 check): $_"
                $null
            }

            $hasLowPrivEnrollment13 = $false
            $enrollmentPrincipals13 = @()
            if ($templateAcl13) {
                foreach ($ace in $templateAcl13.Access) {
                    if ($ace.ActiveDirectoryRights -match 'ExtendedRight|GenericAll') {
                        $principalName = $ace.IdentityReference.Value
                        foreach ($lowPriv in $lowPrivilegedPrincipals) {
                            if ($principalName -match [regex]::Escape($lowPriv)) {
                                $hasLowPrivEnrollment13 = $true
                                $enrollmentPrincipals13 += $principalName
                            }
                        }
                    }
                }
            }
            $enrollmentPrincipals13 = @($enrollmentPrincipals13 | Select-Object -Unique)

            if ($hasLowPrivEnrollment13) {
                $linkedGroups = @($linkedGroups | Select-Object -Unique)
                $finding = [ADSecurityFinding]::new()
                $finding.Category = 'Certificate Services'
                $finding.Issue = 'Certificate Template Issuance Policy Linked to Privileged Group (ESC13)'
                $finding.Severity = 'Critical'
                $finding.SeverityLevel = 4
                $finding.AffectedObject = $templateName13
                $finding.Description = "Certificate template '$templateName13' carries an Issuance Policy OID linked (via msDS-OIDToGroupLink) to group(s): $($linkedGroups -join ', '). The template also has a client-authentication-capable EKU and allows enrollment by low-privileged principal(s): $($enrollmentPrincipals13 -join ', ')."
                $finding.Impact = "Anyone who enrolls for and authenticates with a certificate from this template is automatically treated as a member of the linked group for the duration of that authentication - a group-membership grant that never shows up in any group-membership audit, since it comes from the certificate's policy OID rather than an actual group the account belongs to."
                $finding.Remediation = "Remove the Issuance Policy OID's group link (msDS-OIDToGroupLink) unless this is a deliberate, understood AD FS claims-based scenario, or restrict this template's enrollment to only principals that should legitimately gain the linked group's membership."
                $finding.EstimatedEffort = 'Medium - confirm whether the OID-to-group link is an intentional AD FS claims scenario before removing it, since removing it changes real, currently-working claims-based access for legitimate users too.'
                $finding.KnownRisks = 'Removing the group link breaks any legitimate AD FS claims-based access that currently depends on it - confirm the link is unintentional/unused before removing.'
                $finding.BackupRollback = 'Easy - restore the msDS-OIDToGroupLink value on the OID object if needed; effective immediately.'
                $finding.Details = @{
                    DistinguishedName    = $template.DistinguishedName
                    LinkedGroups         = $linkedGroups -join '; '
                    EnrollmentPrincipals = $enrollmentPrincipals13 -join '; '
                    ESCType              = 'ESC13'
                }
                $findings += $finding
            }
        }
    }

    # -------------------------------------------------------------------
    # ESC15 (EKUwu / Schema V1 EKU injection, CVE-2024-49019)
    # -------------------------------------------------------------------
    # An undocumented Microsoft AD CS vulnerability: a Schema Version 1
    # certificate template has no application-policy/EKU extension
    # enforced by the CA the way Schema V2+ templates do, so a requester
    # can inject arbitrary Application Policy OIDs (EKUs) into the CSR
    # itself, bypassing whatever EKU the template's own configuration
    # would otherwise imply - including injecting Client Authentication
    # to impersonate another account. Reuses the exact same template
    # enumeration and low-privilege-enrollment ACL read already used
    # above for ESC4/ESC13, plus the same manager-approval-gate check
    # (CT_FLAG_PEND_ALL_REQUESTS) already used by the high-risk-without-
    # approval check below - no new AD query.
    foreach ($template in $certTemplates) {
        $templateName15 = if ($template.displayName) { $template.displayName } else { $template.Name }

        $schemaVersion15 = $template.'msPKI-Template-Schema-Version'
        if ($schemaVersion15 -ne 1) { continue }

        $templateAcl15 = try {
            (Get-ADObject -Identity $template.DistinguishedName -Properties nTSecurityDescriptor -Server $__adServer -ErrorAction Stop).nTSecurityDescriptor
        }
        catch {
            Write-Verbose "Test-ADCSExtended: could not get ACL for template '$templateName15' (ESC15 check): $_"
            $null
        }

        $hasLowPrivEnrollment15 = $false
        $enrollmentPrincipals15 = @()
        if ($templateAcl15) {
            foreach ($ace in $templateAcl15.Access) {
                if ($ace.ActiveDirectoryRights -match 'ExtendedRight|GenericAll') {
                    $principalName = $ace.IdentityReference.Value
                    foreach ($lowPriv in $lowPrivilegedPrincipals) {
                        if ($principalName -match [regex]::Escape($lowPriv)) {
                            $hasLowPrivEnrollment15 = $true
                            $enrollmentPrincipals15 += $principalName
                        }
                    }
                }
            }
        }
        $enrollmentPrincipals15 = @($enrollmentPrincipals15 | Select-Object -Unique)
        if (-not $hasLowPrivEnrollment15) { continue }

        # CT_FLAG_PEND_ALL_REQUESTS = 0x2 (manager approval required) -
        # same bit, same helper convention as the high-risk-without-
        # approval check below.
        $enrollmentFlag15 = $template.'msPKI-Enrollment-Flag'
        $requiresApproval15 = [bool]([int64]($enrollmentFlag15) -band 2)
        if ($requiresApproval15) { continue }

        $finding = [ADSecurityFinding]::new()
        $finding.Category = 'Certificate Services'
        $finding.Issue = 'Certificate Template Vulnerable to Schema V1 EKU Injection (ESC15)'
        $finding.Severity = 'Critical'
        $finding.SeverityLevel = 4
        $finding.AffectedObject = $templateName15
        $finding.Description = "Certificate template '$templateName15' is Schema Version 1 (msPKI-Template-Schema-Version = 1), allows enrollment by low-privileged principal(s) ($($enrollmentPrincipals15 -join ', ')), and does not require manager approval (CT_FLAG_PEND_ALL_REQUESTS is not set)."
        $finding.Impact = "CVE-2024-49019 ('EKUwu'): on a Schema Version 1 template, the CA does not constrain the Application Policy OIDs (Extended Key Usages) a requester can inject into the CSR itself, regardless of the template's own declared EKUs. A low-privileged enrollee can inject Client Authentication (or another sensitive EKU) and obtain a certificate usable to authenticate as another account, including a privileged one - functionally similar in outcome to ESC1/ESC13 but reachable through a different, undocumented mechanism specific to Schema V1 templates."
        $finding.Remediation = "Duplicate this template as a Schema Version 2 or later template (which enforces the CA-side EKU/application-policy constraint) and retire the Schema V1 original, or restrict enrollment on the existing template to trusted administrators only, or require manager approval (CT_FLAG_PEND_ALL_REQUESTS) as an interim mitigation. Apply the November 2024 security update (CVE-2024-49019, disclosed by TrustedSec and patched by Microsoft on November 12, 2024) to the issuing CA(s), which addresses the underlying vulnerability."
        $finding.EstimatedEffort = 'Medium - duplicating a template as Schema V2+ and re-pointing enrollment is a routine AD CS operation, but requires confirming which systems currently enroll against the V1 original before retiring it.'
        $finding.KnownRisks = 'Retiring a Schema V1 template can break legacy clients or workflows (e.g. very old Windows Server versions, or agents predating Schema V2 support) that specifically enroll against a V1 template - confirm no legitimate dependency before retiring rather than duplicating.'
        $finding.BackupRollback = 'Easy - the original Schema V1 template is unaffected by publishing a new V2+ duplicate alongside it; only retiring/unpublishing the V1 original needs to be reversible (re-publish it) if an unexpected dependency surfaces.'
        $finding.Details = @{
            DistinguishedName    = $template.DistinguishedName
            SchemaVersion        = $schemaVersion15
            EnrollmentPrincipals = $enrollmentPrincipals15 -join '; '
            RequiresApproval     = $requiresApproval15
            ESCType              = 'ESC15'
            Cve                  = 'CVE-2024-49019'
        }
        $findings += $finding
    }

    # -------------------------------------------------------------------
    # High-risk-without-approval check (snapshot-aware; attribute-only)
    # Deliberately distinct from ESC1 (SAN + low-priv enrollment) and ESC2
    # (no EKU / Any-Purpose): this flags the absence of the manager
    # approval gate on templates carrying either risky property.
    # -------------------------------------------------------------------
    foreach ($template in $certTemplates) {
        $templateName = if ($template.displayName) { $template.displayName } else { $template.Name }

        $certNameFlag = $template.'msPKI-Certificate-Name-Flag'
        $enrollmentFlag = $template.'msPKI-Enrollment-Flag'
        $ekus = $template.'msPKI-Certificate-Application-Policy'
        $ekusV1 = $template.'pKIExtendedKeyUsage'

        $allowsSan = [bool]([int64]($certNameFlag) -band 1)                        # CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT
        $anyPurpose = ($ekus -contains '2.5.29.37.0') -or ($ekusV1 -contains '2.5.29.37.0')
        $requiresApproval = [bool]([int64]($enrollmentFlag) -band 2)               # CT_FLAG_PEND_ALL_REQUESTS

        if (($allowsSan -or $anyPurpose) -and -not $requiresApproval) {
            $finding = [ADSecurityFinding]::new()
            $finding.Category = 'Certificate Services'
            $finding.Issue = 'Certificate Template Allows High-Risk Enrollment Without Manager Approval'
            $finding.Severity = 'High'
            $finding.SeverityLevel = 3
            $finding.AffectedObject = $templateName
            $finding.Description = "Certificate template '$templateName' allows $(if ($allowsSan) { 'enrollee-supplied subject/SAN' }) $(if ($allowsSan -and $anyPurpose) { 'and' }) $(if ($anyPurpose) { 'an Any-Purpose EKU' }) without requiring CA manager approval (CT_FLAG_PEND_ALL_REQUESTS is not set)."
            $finding.Impact = "Certificates matching this template are issued automatically with no human review, removing a compensating control that would otherwise catch abuse of the risky template properties."
            $finding.Remediation = "Require manager approval for this template (set CT_FLAG_PEND_ALL_REQUESTS) until the SAN/Any-Purpose properties can be removed or enrollment can be restricted."
            $finding.EstimatedEffort = 'Low - toggling the "CA certificate manager approval" flag on one template.'
            $finding.KnownRisks = 'Enabling manager approval adds a manual approval step that will delay or block any automated enrollment workflow (autoenrollment, ACME-style automated issuance) that currently assumes instant issuance.'
            $finding.BackupRollback = 'Easy - untick the approval requirement; effective immediately for new requests, no data loss.'
            $finding.Details = @{
                DistinguishedName = $template.DistinguishedName
                AllowsSan         = $allowsSan
                AnyPurposeEku     = $anyPurpose
                RequiresApproval  = $requiresApproval
            }
            $findings += $finding
        }
    }

    # -------------------------------------------------------------------
    # ESC8: CA web enrollment over HTTP without EPA (live only)
    # -------------------------------------------------------------------
    foreach ($ca in $certAuthorities) {
        $caName = $ca.Name
        $caHost = $ca.dNSHostName
        if (-not $caHost) {
            Write-Verbose "Test-ADCSExtended: CA '$caName' has no dNSHostName; skipping ESC8 probe."
            continue
        }

        try {
            $webEnrollState = Invoke-ADQueryWithRetry -OperationName "Probe CA web enrollment on $caHost" -Query {
                Invoke-Command -ComputerName $caHost -ErrorAction Stop -ScriptBlock {
                    $result = [PSCustomObject]@{
                        CertSrvVDirPresent = $false
                        EpaRequired        = $null
                        Error              = $null
                    }
                    try {
                        Import-Module WebAdministration -ErrorAction Stop
                        $vdir = Get-WebApplication -Site 'Default Web Site' -Name 'CertSrv' -ErrorAction SilentlyContinue
                        if ($vdir) {
                            $result.CertSrvVDirPresent = $true
                            try {
                                $epa = Get-WebConfigurationProperty -PSPath 'IIS:\Sites\Default Web Site\CertSrv' `
                                    -Filter 'system.webServer/security/authentication/windowsAuthentication' `
                                    -Name 'extendedProtection.tokenChecking' -ErrorAction Stop
                                $result.EpaRequired = ($epa.Value -eq 'Require')
                            }
                            catch {
                                $result.EpaRequired = $null
                            }
                        }
                    }
                    catch {
                        $result.Error = "$_"
                    }
                    return $result
                }
            }
        }
        catch {
            Write-Verbose "Test-ADCSExtended: could not probe CA host '$caHost' for web enrollment state: $_"
            $webEnrollState = $null
        }

        if ($webEnrollState -and $webEnrollState.CertSrvVDirPresent) {
            $epaMissing = ($webEnrollState.EpaRequired -ne $true)
            if ($epaMissing) {
                $finding = [ADSecurityFinding]::new()
                $finding.Category = 'Certificate Services'
                $finding.Issue = 'CA Web Enrollment over HTTP (ESC8)'
                $finding.Severity = 'Critical'
                $finding.SeverityLevel = 4
                $finding.AffectedObject = $caName
                $finding.Description = "Certificate Authority '$caName' ($caHost) has the CertSrv web enrollment endpoint installed without Extended Protection for Authentication (EPA) enforced."
                $finding.Impact = "An attacker who coerces a privileged host (e.g. a Domain Controller) to authenticate to them can relay that NTLM authentication to the CA's HTTP enrollment endpoint and obtain a certificate as that host/account, leading to domain compromise."
                $finding.Remediation = "Disable HTTP(S) web enrollment if unused, or require Extended Protection for Authentication ('Require') on the CertSrv virtual directory and enforce HTTPS with channel binding."
                $finding.EstimatedEffort = 'Medium - requires enabling HTTPS web enrollment (certificate + IIS binding) and usually coordination with whoever manages the CA''s IIS instance; confirm no client submits enrollment requests over plain HTTP first.'
                $finding.KnownRisks = 'Enforcing HTTPS-only web enrollment can break legacy clients or scripts that submit requests over plain HTTP until they''re updated to the HTTPS endpoint.'
                $finding.BackupRollback = 'Moderate - revert the IIS binding/auth settings and re-enable the HTTP endpoint if needed; requires an IIS restart but no data loss.'
                $finding.OperationalNotes = 'HTTPS alone doesn''t fully close ESC8''s NTLM relay risk without Extended Protection for Authentication (EPA) also enabled - consider enabling EPA on the enrollment endpoint at the same time.'
                $finding.Details = @{
                    DistinguishedName = $ca.DistinguishedName
                    CAHost            = $caHost
                    EpaRequired       = $webEnrollState.EpaRequired
                    ESCType           = 'ESC8'
                }
                $findings += $finding
            }
        }
        elseif ($webEnrollState -and $webEnrollState.Error) {
            Write-Verbose "Test-ADCSExtended: web enrollment probe on '$caHost' reported: $($webEnrollState.Error)"
        }
    }

    # -------------------------------------------------------------------
    # ROCA / weak signature sweep of the CA's own certificate(s)
    # (snapshot-aware: uses cACertificate already captured on CA objects).
    # -------------------------------------------------------------------
    $weakCertResults = [System.Collections.ArrayList]::new()

    foreach ($ca in $certAuthorities) {
        foreach ($b in @($ca.'cACertificate')) {
            if (-not $b) { continue }
            $result = Test-ADCSWeakCertificate -Bytes $b -Source "CA:$($ca.Name)"
            if ($result) { [void]$weakCertResults.Add($result) }
        }
    }

    # -------------------------------------------------------------------
    # NTAuth / AIA / Root store sweep
    # -------------------------------------------------------------------
    try {
        $pkiContainer = "CN=Public Key Services,CN=Services,$configContext"
        $storeTargets = @{
            'NTAuth' = "CN=NTAuthCertificates,$pkiContainer"
            'AIA'    = "CN=AIA,$pkiContainer"
            'Root'   = "CN=Certification Authorities,$pkiContainer"
        }

        foreach ($storeName in $storeTargets.Keys) {
            $blobs = Get-ADCSCertificateBlob -ContainerDN $storeTargets[$storeName] -Server $__adServer
            foreach ($blob in $blobs) {
                $result = Test-ADCSWeakCertificate -Bytes $blob.Bytes -Source "$storeName`:$($blob.Source)"
                if ($result) { [void]$weakCertResults.Add($result) }
            }
        }
    }
    catch {
        Write-Verbose "Test-ADCSExtended: could not sweep NTAuth/AIA/Root store: $_"
    }

    foreach ($weak in $weakCertResults) {
        if ($weak.RocaCandidate) {
            $finding = [ADSecurityFinding]::new()
            $finding.Category = 'Certificate Services'
            $finding.Issue = 'ROCA-Vulnerable Certificate Key'
            $finding.Severity = 'High'
            $finding.SeverityLevel = 3
            $finding.AffectedObject = $weak.Source
            $finding.Description = "Certificate '$($weak.Subject)' (thumbprint $($weak.Thumbprint)) from $($weak.Source) matches the ROCA (CVE-2017-15361) weak-key fingerprint for RSA keys generated by the affected Infineon RSALib."
            $finding.Impact = "ROCA-vulnerable RSA keys can, with sufficient compute, have their private key factored from the public key alone, fully compromising anything the certificate protects or authenticates."
            $finding.Remediation = "Confirm with a dedicated ROCA-detection tool, then revoke and reissue the certificate with a key generated by an unaffected library."
            $finding.EstimatedEffort = 'High - revoking and reissuing a certificate requires coordinating with every consumer of that certificate, since revocation invalidates trust immediately and may need a maintenance window if the certificate is in active use (e.g. smart card logon, TLS).'
            $finding.KnownRisks = 'ROCA-vulnerable RSA keys can, with sufficient compute, have their private key factored from the public key alone (CVE-2017-15361), so this is a confirmed, documented weakness, not a hypothetical one; revoking the certificate breaks authentication/encryption for everything relying on it until the replacement is deployed.'
            $finding.BackupRollback = 'Hard/Limited - a revoked certificate cannot be un-revoked; the only path forward is issuing a new one with a key from an unaffected library, so keep the old certificate available read-only for verifying historically-signed artifacts if that''s needed.'
            $finding.Details = @{
                Source             = $weak.Source
                Subject            = $weak.Subject
                Thumbprint         = $weak.Thumbprint
                KeySize            = $weak.KeySize
                SignatureAlgorithm = $weak.SignatureAlgorithm
                Note               = 'Probabilistic fingerprint test; confirm before remediation.'
            }
            $findings += $finding
        }

        if ($weak.WeakSignature -or $weak.WeakModulus) {
            $reasons = @()
            if ($weak.WeakSignature) { $reasons += "weak signature algorithm ($($weak.SignatureAlgorithm))" }
            if ($weak.WeakModulus) { $reasons += "RSA key size below 2048 bits ($($weak.KeySize) bits)" }

            $finding = [ADSecurityFinding]::new()
            $finding.Category = 'Certificate Services'
            $finding.Issue = 'Weak Signature Algorithm in PKI Trust Store'
            $finding.Severity = 'Medium'
            $finding.SeverityLevel = 2
            $finding.AffectedObject = $weak.Source
            $finding.Description = "Certificate '$($weak.Subject)' (thumbprint $($weak.Thumbprint)) from $($weak.Source) has $($reasons -join ' and ')."
            $finding.Impact = "Weak signature algorithms (MD2/MD4/MD5/SHA0/SHA1) or undersized RSA keys undermine the integrity of the certificate chain and any trust decisions made against it."
            $finding.Remediation = "Reissue the certificate with SHA-256 (or better) and an RSA key of at least 2048 bits (3072+ recommended for CA certificates)."
            $finding.EstimatedEffort = 'Medium - reissuing affected certificates with a stronger signature algorithm (e.g. SHA-256+) and coordinating with every consumer of the old chain.'
            $finding.KnownRisks = 'Modern OSes and browsers already reject SHA-1-signed certificates, but legacy embedded devices or older client OSes may only trust the SHA-1 chain and could lose connectivity until they''re updated to trust the new one.'
            $finding.BackupRollback = 'Hard/Limited - like other certificate revocation/reissuance, this isn''t reversible to the old certificate''s validity; keep the old CA certificate available for verifying already-issued signatures if needed.'
            $finding.Details = @{
                Source             = $weak.Source
                Subject            = $weak.Subject
                Thumbprint         = $weak.Thumbprint
                KeySize            = $weak.KeySize
                SignatureAlgorithm = $weak.SignatureAlgorithm
                NotAfter           = $weak.NotAfter
            }
            $findings += $finding
        }
    }

    Write-Verbose "AD CS extended audit complete. Found $($findings.Count) issues."
    return $findings
}

#endregion

#region CA Chase-Fallback Exposure (CVE-2026-54121 / "Certighost")

function Test-ADCSChaseFallback {
    <#
    .SYNOPSIS
        Detects Enterprise CAs with the EDITF_ENABLECHASECLIENTDC policy
        flag set, the configuration condition CVE-2026-54121 ("Certighost")
        abuses to obtain a certificate asserting a Domain Controller's
        identity from a low-privileged, attacker-controlled account.
    .DESCRIPTION
        Reads each discovered Enterprise CA's policy\EditFlags registry
        value (same registry key family as the CA policy-module settings
        this module already reads) and checks the EDITF_ENABLECHASECLIENTDC
        bit (0x00100000). When set, the CA honors a requester-supplied
        client-DC ("cdc") hint during certificate-request identity
        resolution; on an unpatched CA this hint is used without
        confirming it actually resolves to a genuine DC object, letting an
        attacker point the CA at a host they control and obtain a
        certificate asserting a DC's identity, enabling DC impersonation
        and DCSync-class domain compromise.

        This is a configuration exposure check, not a patch-level check:
        the flag is the exposure indicator regardless of whether the CA
        host has installed Microsoft's July 14, 2026 security update
        (which validates the chase target before contacting it, but does
        not clear the flag). A patched CA with the flag still set remains
        configured in the historically risky state and is still flagged
        here, as defense-in-depth - the flag can be re-enabled later via
        policy, imaging, or an admin action independent of patch state.

        Also reads two related per-CA registry values from the SAME
        remote-registry connection, at essentially no extra cost:
          - ESC6 (EDITF_ATTRIBUTESUBJECTALTNAME2, same policy\EditFlags
            value as the chase-fallback bit above).
          - ESC11 (IF_ENFORCEENCRYPTICERTREQUEST absent from
            InterfaceFlags): the RPC enrollment interface accepting
            unencrypted requests, enabling NTLM relay to the CA.
          - ESC16 (szOID_NTDS_CA_SECURITY_EXT present in
            policy\DisableExtensionList): CA-wide disabling of the
            SID-binding security extension, the CA-wide equivalent of the
            per-template ESC9 check in Test-ADCSExtended.
        The function name/CVE-focused Synopsis predates these additions;
        left as-is since renaming an already-exported function is a
        breaking change, same reasoning ESC6 already established here.

        Detection only: reads registry values per discovered CA. No
        certificate requests, no PoC/exploitation traffic, no coercion.
    .OUTPUTS
        [ADSecurityFinding[]]
    #>
    [CmdletBinding()]
    param()

    Write-Verbose "Starting AD CS chase-fallback exposure audit (CVE-2026-54121 / Certighost / ESC6 / ESC11 / ESC16)..."
    $findings = @()

    # Bit value confirmed against independent public technical write-ups of
    # CVE-2026-54121 (0x00100000 / 1048576) - not redefined ad hoc elsewhere
    # in this module, since no existing EDITF_* constant was already defined
    # here to reuse.
    $editfEnableChaseClientDc = 0x00100000

    # EDITF_ATTRIBUTESUBJECTALTNAME2 (0x00040000) - a CA-wide policy flag
    # that lets ANY certificate template on the CA accept a caller-supplied
    # Subject Alternative Name (SAN) in the certificate request, regardless
    # of the individual template's own "Enrollee Supplies Subject" setting.
    # This is the well-known ESC6 misconfiguration: with this flag set, a
    # low-privileged requester can obtain a certificate asserting the
    # identity of any other user or computer object - including Tier-0
    # accounts - via a template that would otherwise be safe, since the
    # flag operates at the CA level, above and independent of per-template
    # ACLs/settings. Read from the SAME already-fetched policy\EditFlags
    # registry value as the chase-fallback check above - one remote read,
    # two independent bit checks - explicitly named as a top AD CS
    # mitigation in ASD/CISA/NSA/CCCS/NCSC-NZ/NCSC-UK's "Detecting and
    # mitigating Active Directory compromises" (Sept 2026): "Ensure that
    # the CA is not configured with the EDITF_ATTRIBUTESUBJECTALTNAME2 flag."
    $editfAttributeSubjectAltName2 = 0x00040000

    $certAuthorities = @()
    $adcsInstalled = $false

    try {
        $__adServer = Get-ADSecurityAuditTargetServerValue
        $configContext = Get-ADRootDSEValue -Property configurationNamingContext -Server $__adServer
        $pkiContainer = "CN=Public Key Services,CN=Services,$configContext"

        $certAuthorities = @(Invoke-ADQueryWithRetry -OperationName 'Get enrollment services (ADCS chase-fallback audit)' -Query {
            Get-ADObject -SearchBase "CN=Enrollment Services,$pkiContainer" -SearchScope OneLevel -Filter * -Properties dNSHostName -Server $__adServer -ErrorAction Stop
        })
        $adcsInstalled = $true
    }
    catch {
        Write-Verbose "Test-ADCSChaseFallback: AD Certificate Services not found or accessible. Skipping chase-fallback audit."
        return $findings
    }

    if (-not $adcsInstalled -or -not $certAuthorities -or @($certAuthorities).Count -eq 0) {
        Write-Verbose "Test-ADCSChaseFallback: no Enterprise CAs discovered; skipping."
        return $findings
    }

    foreach ($ca in $certAuthorities) {
        $caName = $ca.Name
        $caHost = $ca.dNSHostName
        if (-not $caHost) {
            Write-Verbose "Test-ADCSChaseFallback: CA '$caName' has no dNSHostName; skipping."
            continue
        }

        try {
            $editFlagsResult = Invoke-ADQueryWithRetry -OperationName "Read policy\EditFlags on $caHost" -Query {
                Invoke-Command -ComputerName $caHost -ErrorAction Stop -ScriptBlock {
                    param($CaSanitizedName)
                    $result = [PSCustomObject]@{
                        EditFlagsRead = $false
                        EditFlags     = $null
                        InterfaceFlagsRead = $false
                        InterfaceFlags     = $null
                        DisableExtensionListRead = $false
                        DisableExtensionList     = $null
                        Error         = $null
                    }
                    try {
                        # Same registry family as this module's other CA
                        # policy-module reads:
                        # HKLM\SYSTEM\CurrentControlSet\Services\CertSvc\Configuration\<CA
                        # sanitized name>\PolicyModules\CertificateAuthority_MicrosoftDefault.Policy
                        #
                        # A CA's registry key name (its "sanitized name") can
                        # differ from its AD common name if the CN contains
                        # characters not valid in a registry key. Prefer an
                        # exact match against the AD-supplied name first;
                        # fall back to the sole child key when there's only
                        # one CA configured on the host (by far the common
                        # case), and otherwise report ambiguity rather than
                        # silently guessing which CA's flags we're reading.
                        $caRegNames = @(Get-ChildItem 'HKLM:\SYSTEM\CurrentControlSet\Services\CertSvc\Configuration' -ErrorAction Stop | Select-Object -ExpandProperty PSChildName)
                        $matchedRegCaName = $null
                        if ($caRegNames -contains $CaSanitizedName) {
                            $matchedRegCaName = $CaSanitizedName
                        }
                        elseif (@($caRegNames).Count -eq 1) {
                            $matchedRegCaName = $caRegNames[0]
                        }

                        if ($matchedRegCaName) {
                            $policyPath = "HKLM:\SYSTEM\CurrentControlSet\Services\CertSvc\Configuration\$matchedRegCaName\PolicyModules\CertificateAuthority_MicrosoftDefault.Policy"
                            if (Test-Path $policyPath) {
                                $prop = Get-ItemProperty -Path $policyPath -Name 'EditFlags' -ErrorAction Stop
                                $result.EditFlagsRead = $true
                                $result.EditFlags = [int]$prop.EditFlags

                                # ESC16: same PolicyModules key as EditFlags -
                                # DisableExtensionList is a REG_MULTI_SZ list
                                # of OIDs the CA omits from every certificate
                                # it issues, regardless of template. Read
                                # opportunistically; its absence just means
                                # no extensions are CA-wide disabled (the
                                # normal, safe state), not an error.
                                try {
                                    $extProp = Get-ItemProperty -Path $policyPath -Name 'DisableExtensionList' -ErrorAction Stop
                                    $result.DisableExtensionListRead = $true
                                    $result.DisableExtensionList = @($extProp.DisableExtensionList)
                                }
                                catch {
                                    $result.DisableExtensionListRead = $true
                                    $result.DisableExtensionList = @()
                                }
                            }
                            else {
                                $result.Error = "Policy module registry key not found under CA '$matchedRegCaName'."
                            }

                            # ESC11: a SEPARATE registry value from EditFlags/
                            # DisableExtensionList - directly under the CA's
                            # own configuration key, not under PolicyModules.
                            try {
                                $ifPath = "HKLM:\SYSTEM\CurrentControlSet\Services\CertSvc\Configuration\$matchedRegCaName"
                                $ifProp = Get-ItemProperty -Path $ifPath -Name 'InterfaceFlags' -ErrorAction Stop
                                $result.InterfaceFlagsRead = $true
                                $result.InterfaceFlags = [int]$ifProp.InterfaceFlags
                            }
                            catch {
                                # Leave InterfaceFlagsRead = $false - distinct
                                # from "read and the bit was absent", same
                                # reasoning as the EditFlags/DisableExtension
                                # reads: an inability to read the value should
                                # never be silently treated as "vulnerable".
                            }
                        }
                        else {
                            $result.Error = "Could not unambiguously match AD CA name '$CaSanitizedName' to a registry CA key; found: $($caRegNames -join ', ')."
                        }
                    }
                    catch {
                        $result.Error = "$_"
                    }
                    return $result
                } -ArgumentList $caName
            }
        }
        catch {
            Write-Verbose "Test-ADCSChaseFallback: could not read policy\EditFlags on CA host '$caHost': $_"
            $editFlagsResult = $null
        }

        if (-not $editFlagsResult -or -not $editFlagsResult.EditFlagsRead) {
            if ($editFlagsResult -and $editFlagsResult.Error) {
                Write-Verbose "Test-ADCSChaseFallback: EditFlags probe on '$caHost' reported: $($editFlagsResult.Error)"
            }
            continue
        }

        $chaseFallbackEnabled = (($editFlagsResult.EditFlags -band $editfEnableChaseClientDc) -ne 0)

        if ($chaseFallbackEnabled) {
            $finding = [ADSecurityFinding]::new()
            $finding.Category = 'Certificate Services'
            $finding.Issue = 'CA Chase-Fallback Enabled (CVE-2026-54121 / Certighost Exposure)'
            $finding.Severity = 'Critical'
            $finding.SeverityLevel = 4
            $finding.AffectedObject = "$caName ($caHost)"
            $finding.Description = "Certificate Authority '$caName' ($caHost) has the EDITF_ENABLECHASECLIENTDC policy flag set on its policy\EditFlags registry value. This enables the CA's client-DC 'chase' fallback, in which the CA will contact a requester-supplied host to resolve identity data during certificate issuance."
            $finding.Impact = "CVE-2026-54121 (`"Certighost`", CVSS 8.8) abuses this chase-fallback behavior: an authenticated, low-privileged attacker with network access to the CA can supply a client-DC hint pointing at an attacker-controlled host, causing the CA to obtain and use that host's identity data when issuing a certificate. On an unpatched CA this can result in a certificate asserting a Domain Controller's identity being issued to the attacker, enabling DC impersonation and DCSync-class full domain compromise. The flag is the exposure indicator independent of the CA's patch level: Microsoft's July 14, 2026 update adds chase-target validation but does not clear this flag, so a patched CA with the flag still set remains configured in the historically risky state and can become exploitable again if the flag is re-enabled by policy, imaging, or later admin action."
            $finding.Remediation = "Apply Microsoft's July 14, 2026 security update for CVE-2026-54121, which adds chase-target validation to the CA. Independently, clear the flag as defense-in-depth (or as an immediate stopgap if the update cannot be applied yet): certutil -config `"$caName`" -setreg policy\EditFlags -EDITF_ENABLECHASECLIENTDC, then restart Certificate Services (Restart-Service CertSvc -Force). Test in staging first if cross-domain/cross-forest enrollment relies on the chase fallback, since disabling it will break that use case until the CA can reach the relevant DCs directly."
            $finding.EstimatedEffort = 'High - before disabling the flag or patching, requires discovering which cross-domain/cross-forest enrollment workflows (if any) depend on the chase fallback across every CA, since Microsoft''s own advisory notes the registry mitigation was validated only in a lab and should be tested per-CA before production rollout.'
            $finding.KnownRisks = 'Clearing the flag (or the patch''s added validation) can break certificate enrollment for legitimate cross-domain or cross-forest clients that rely on the CA''s chase behavior to resolve a client-DC hint the CA cannot otherwise reach directly.'
            $finding.BackupRollback = 'Easy - the change is a single registry value; if a legitimate enrollment workflow breaks, re-enable EDITF_ENABLECHASECLIENTDC via certutil and restart CertSvc to restore the prior behavior immediately, with no data loss.'
            $finding.OperationalNotes = 'Re-enabling the flag as a rollback restores the CVE-2026-54121 exposure, so treat it as strictly temporary and monitor Certificate Services event ID 4886 (a cert request carrying a client-DC hint that doesn''t match a known DC) while investigating any dependency.'
            $finding.Details = @{
                DistinguishedName = $ca.DistinguishedName
                CAHost            = $caHost
                EditFlags         = ('0x{0:X}' -f $editFlagsResult.EditFlags)
                EditFlagBit       = 'EDITF_ENABLECHASECLIENTDC (0x00100000)'
                CVE               = 'CVE-2026-54121'
                PatchDate         = '2026-07-14'
            }
            $findings += $finding
        }

        $sanFlagEnabled = (($editFlagsResult.EditFlags -band $editfAttributeSubjectAltName2) -ne 0)

        if ($sanFlagEnabled) {
            $finding = [ADSecurityFinding]::new()
            $finding.Category = 'Certificate Services'
            $finding.Issue = 'CA-Wide SAN Attribute Flag Enabled (ESC6)'
            $finding.Severity = 'Critical'
            $finding.SeverityLevel = 4
            $finding.AffectedObject = "$caName ($caHost)"
            $finding.Description = "Certificate Authority '$caName' ($caHost) has the EDITF_ATTRIBUTESUBJECTALTNAME2 policy flag set on its policy\EditFlags registry value. This allows a Subject Alternative Name (SAN) to be supplied in a certificate request for ANY certificate template on this CA, regardless of that template's own 'Enrollee Supplies Subject' setting."
            $finding.Impact = "This is the well-known ESC6 misconfiguration: because the flag operates CA-wide rather than per-template, a low-privileged requester can supply an arbitrary SAN - including the identity of a Tier-0 account - when enrolling against ANY template on this CA that permits client authentication, even templates whose own configuration would otherwise be considered safe. The resulting certificate can then be used to authenticate as the impersonated identity."
            $finding.Remediation = "Clear the EDITF_ATTRIBUTESUBJECTALTNAME2 flag: certutil -config `"$caName`" -setreg policy\EditFlags -EDITF_ATTRIBUTESUBJECTALTNAME2, then restart Certificate Services (Restart-Service CertSvc -Force). Confirm no legitimate enrollment workflow relies on CA-wide SAN supply before disabling - if SAN supply is genuinely needed for a specific template, configure it on that template individually instead ('Enrollee Supplies Subject') rather than CA-wide."
            $finding.EstimatedEffort = 'Medium - a single registry flag, but requires first identifying which templates/workflows (if any) currently rely on CA-wide SAN supply so their enrollment isn''t broken.'
            $finding.KnownRisks = 'Clearing this flag breaks enrollment for any legitimate workflow that currently depends on supplying a SAN CA-wide (rather than via an individual template''s own Enrollee Supplies Subject setting) - identify and migrate those workflows to per-template configuration first.'
            $finding.BackupRollback = 'Easy - the change is a single registry value; re-enable via certutil and restart CertSvc to restore the prior behavior immediately if something breaks, with no data loss.'
            $finding.Details = @{
                DistinguishedName = $ca.DistinguishedName
                CAHost            = $caHost
                EditFlags         = ('0x{0:X}' -f $editFlagsResult.EditFlags)
                EditFlagBit       = 'EDITF_ATTRIBUTESUBJECTALTNAME2 (0x00040000)'
            }
            $findings += $finding
        }

        # ESC11: RPC enrollment interface not requiring encryption
        if ($editFlagsResult.InterfaceFlagsRead) {
            $interfaceFlags = $editFlagsResult.InterfaceFlags
            $encryptEnforced = (($interfaceFlags -band 0x200) -ne 0)

            if (-not $encryptEnforced) {
                $finding = [ADSecurityFinding]::new()
                $finding.Category = 'Certificate Services'
                $finding.Issue = 'CA RPC Enrollment Encryption Not Enforced (ESC11)'
                $finding.Severity = 'Critical'
                $finding.SeverityLevel = 4
                $finding.AffectedObject = "$caName ($caHost)"
                $finding.Description = "Certificate Authority '$caName' ($caHost) does not have the IF_ENFORCEENCRYPTICERTREQUEST flag set on its InterfaceFlags registry value - the ICPR RPC certificate-enrollment interface accepts requests without requiring packet-level encryption."
                $finding.Impact = "Without IF_ENFORCEENCRYPTICERTREQUEST, the CA's RPC enrollment interface accepts connections below RPC_C_AUTHN_LEVEL_PKT_PRIVACY, making it vulnerable to NTLM relay: an attacker who coerces authentication from a privileged machine (e.g. a Domain Controller, via PetitPotam/PrinterBug-style coercion) can relay that authentication over unencrypted RPC to this CA and request a certificate asserting the coerced machine's identity - a direct path to Domain Controller impersonation."
                $finding.Remediation = "Enable the flag: certutil -config `"$caName`" -setreg CA\InterfaceFlags +IF_ENFORCEENCRYPTICERTREQUEST, then restart Certificate Services (Restart-Service CertSvc -Force)."
                $finding.EstimatedEffort = 'Low - a single registry flag; the on-by-default setting is occasionally disabled for legacy client compatibility (e.g. Windows XP), so confirm no such client still enrolls against this CA before enabling.'
                $finding.KnownRisks = 'Enabling packet-privacy enforcement will break enrollment for any client that cannot negotiate RPC_C_AUTHN_LEVEL_PKT_PRIVACY - in practice, only very old (pre-Vista-era) clients, which should not be enrolling in a modern environment regardless.'
                $finding.BackupRollback = 'Easy - the change is a single registry value; revert with certutil -setreg CA\InterfaceFlags -IF_ENFORCEENCRYPTICERTREQUEST and restart CertSvc if something breaks.'
                $finding.Details = @{
                    DistinguishedName = $ca.DistinguishedName
                    CAHost            = $caHost
                    InterfaceFlags    = ('0x{0:X}' -f $interfaceFlags)
                    RequiredBit       = 'IF_ENFORCEENCRYPTICERTREQUEST (0x00000200)'
                    ESCType           = 'ESC11'
                }
                $findings += $finding
            }
        }
        else {
            Write-Verbose "Test-ADCSChaseFallback: could not read InterfaceFlags on '$caHost' for ESC11 check; skipping that check for this CA."
        }

        # ESC16: CA-wide disabling of the SID-binding security extension
        if ($editFlagsResult.DisableExtensionListRead -and $editFlagsResult.DisableExtensionList -contains '1.3.6.1.4.1.311.25.2') {
            $finding = [ADSecurityFinding]::new()
            $finding.Category = 'Certificate Services'
            $finding.Issue = 'CA-Wide Security Extension Disabled (ESC16)'
            $finding.Severity = 'Critical'
            $finding.SeverityLevel = 4
            $finding.AffectedObject = "$caName ($caHost)"
            $finding.Description = "Certificate Authority '$caName' ($caHost) has the SID-binding security extension (szOID_NTDS_CA_SECURITY_EXT, OID 1.3.6.1.4.1.311.25.2) added to its policy\DisableExtensionList - every certificate this CA issues, from every template, omits the SID-binding extension."
            $finding.Impact = "This is functionally identical to ESC9 (Certificate Template Missing Security Extension), but applies CA-wide rather than to one template - every template published by this CA behaves as though CT_FLAG_NO_SECURITY_EXTENSION were set on it individually. Whether this is currently exploitable depends on Domain Controller certificate-mapping enforcement (see the separate ESC10/'Weak Certificate Binding Compensation' finding): under full enforcement on every DC, the KDC rejects a certificate lacking this extension outright, but any DC not yet at full enforcement - or with a CertificateBackdatingCompensation opt-out active - remains exploitable via this CA."
            $finding.Remediation = "Remove the extension from the disabled list: certutil -config `"$caName`" -setreg policy\DisableExtensionList -1.3.6.1.4.1.311.25.2, then restart Certificate Services (Restart-Service CertSvc -Force)."
            $finding.EstimatedEffort = 'Low - a single registry list entry; this setting has no known legitimate ongoing use in a modern (KB5014754+) environment.'
            $finding.KnownRisks = 'Minimal - re-enabling the extension only adds information to newly-issued certificates; it does not change any existing legitimate authentication behavior.'
            $finding.BackupRollback = 'Easy - the change is a single registry value; re-add the OID to DisableExtensionList and restart CertSvc to restore the prior behavior if needed, with no data loss.'
            $finding.Details = @{
                DistinguishedName    = $ca.DistinguishedName
                CAHost               = $caHost
                DisableExtensionList = ($editFlagsResult.DisableExtensionList -join '; ')
                DisabledExtension    = 'szOID_NTDS_CA_SECURITY_EXT (1.3.6.1.4.1.311.25.2)'
                ESCType              = 'ESC16'
            }
            $findings += $finding
        }
    }

    Write-Verbose "AD CS chase-fallback exposure audit complete. Found $($findings.Count) issues."
    return $findings
}

#endregion

#region ESC10: Weak Certificate Binding Compensation (DC-side)

function Test-ADCSWeakCertificateBinding {
    <#
    .SYNOPSIS
        Detects Domain Controllers with an active opt-out from strong
        certificate-mapping enforcement (ESC10).
    .DESCRIPTION
        Historically, ESC10 was framed around the KDC's
        StrongCertificateBindingEnforcement registry value (0 = disabled,
        1 = compatibility, 2 = full enforcement). As of the September 9,
        2025 security update, Microsoft made full enforcement PERMANENT
        and UNCONDITIONAL on every patched Domain Controller - the
        StrongCertificateBindingEnforcement value is no longer honored at
        all once that update is installed, so reading it on a modern,
        patched DC would not accurately reflect the DC's real enforcement
        state and could produce a misleading "still vulnerable" finding
        when the setting is in fact moot.

        The registry lever that still genuinely matters today is
        CertificateBackdatingCompensation (also under
        HKLM\SYSTEM\CurrentControlSet\Services\Kdc): a documented,
        still-honored opt-out that re-permits weak-mapped authentication
        for certificates issued before a configured cutoff (specified in
        days). A DC with this value set to a large or unbounded number of
        days re-opens the same weak-mapping exposure ESC9/ESC16 rely on,
        even on a fully patched DC.

        Each DC is evaluated independently and degrades gracefully if it
        cannot be reached.
    .OUTPUTS
        [ADSecurityFinding[]]
    #>
    [CmdletBinding()]
    param()

    Write-Verbose "Starting weak certificate-binding compensation audit (ESC10)..."
    $findings = @()

    $domainControllers = @()
    try {
        $domainControllers = @(Invoke-ADQueryWithRetry -OperationName 'Get-ADSecurityAuditDomainController (ESC10 audit)' -Query {
            Get-ADSecurityAuditDomainController -Server (Get-ADSecurityAuditTargetServerValue)
        })
    }
    catch {
        Write-Warning "Test-ADCSWeakCertificateBinding: failed to enumerate Domain Controllers: $_"
    }

    if (-not $domainControllers -or $domainControllers.Count -eq 0) {
        Write-Verbose "Test-ADCSWeakCertificateBinding: no Domain Controllers to evaluate; no findings."
        return $findings
    }

    $backdatingDCs = @()

    foreach ($dc in $domainControllers) {
        $dcName = if ($dc.HostName) { $dc.HostName } elseif ($dc.Name) { $dc.Name } else { "$dc" }

        try {
            $backdatingResult = Invoke-ADQueryWithRetry -OperationName "Read CertificateBackdatingCompensation on $dcName" -Query {
                Invoke-Command -ComputerName $dcName -ErrorAction Stop -ScriptBlock {
                    (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Kdc' -Name 'CertificateBackdatingCompensation' -ErrorAction SilentlyContinue).CertificateBackdatingCompensation
                }
            }

            if ($null -ne $backdatingResult -and [int]$backdatingResult -gt 0) {
                $backdatingDCs += [PSCustomObject]@{ DomainController = $dcName; Days = [int]$backdatingResult }
            }
        }
        catch {
            Write-Verbose "Test-ADCSWeakCertificateBinding: could not read CertificateBackdatingCompensation on '$dcName': $_"
        }
    }

    if ($backdatingDCs.Count -gt 0) {
        $dcBullets = ($backdatingDCs | ForEach-Object { "- $($_.DomainController): $($_.Days) day(s)" }) -join "`n"

        $finding = [ADSecurityFinding]::new()
        $finding.Category = 'Certificate Services'
        $finding.Issue = 'Weak Certificate Binding Compensation Enabled (ESC10)'
        $finding.Severity = 'High'
        $finding.SeverityLevel = 3
        $finding.AffectedObject = ($backdatingDCs.DomainController -join ', ')
        $finding.Description = "CertificateBackdatingCompensation is set to a non-zero value on $($backdatingDCs.Count) Domain Controller(s), re-permitting weak certificate-mapping authentication for certificates issued before the configured cutoff:`n$dcBullets"
        $finding.Impact = "Even on a fully patched DC where full strong-mapping enforcement is otherwise permanent, this setting re-opens the weak-mapping window it exists to compensate for. Any certificate issued within the configured day count that lacks a strong SID binding (see ESC9/ESC16) can still authenticate via weak mapping, undermining the enforcement KB5014754 and the September 2025 update were meant to guarantee."
        $finding.Remediation = "Re-issue any legitimately outstanding weak-mapped certificates with strong SID bindings, then remove or zero out CertificateBackdatingCompensation on every affected DC: Remove-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Kdc' -Name 'CertificateBackdatingCompensation'."
        $finding.EstimatedEffort = 'Medium - requires first confirming every certificate relying on the compensation window has been re-issued with strong mapping before removing the opt-out, or authentication for those certificates will break.'
        $finding.KnownRisks = 'Removing this value before all weak-mapped certificates it was covering have been re-issued will break authentication for whatever legitimately still depends on the compensation window - confirm coverage first.'
        $finding.BackupRollback = 'Easy - restore the prior CertificateBackdatingCompensation value if needed; effective immediately, no data loss.'
        $finding.Details = @{
            AffectedDomainControllers = @($backdatingDCs)
            ESCType                   = 'ESC10'
        }
        $findings += $finding
    }

    Write-Verbose "Weak certificate-binding compensation audit complete. Found $($findings.Count) issue(s)."
    return $findings
}

#endregion
